<div>
<p>Una expresión de notación precedida por paréntesis permite el uso de operadores con
para cada uno un número variable de operandos.</p>
<p>Los paréntesis <u>deben</u> encerrar un operando.<br/>
Un operador con sus operandos <u>puede</u> estar entre paréntesis.</p>
<p>Es posible escapar de los caracteres &#39;(&#39; y &#39;)&#39;, cuando este último no debe
definir un operando, agregando justo antes del carácter &#39;\&#39;.</p>
</div>
<hr style="border-color: #ECECEC; color: #ECECEC"/>
<div style="font-style: italic">
<p>Ejemplo: Considere el contexto de la evaluación de un cálculo simple.</p>
Los operadores serían:
<ul>
<li><b>+</b> : operador de suma</li>
<li><b>-</b> : operador de resta</li>
</ul>
Se pueden evaluar las siguientes expresiones:
<ul>
<li><b>+(1)(2)(5)</b> daría 8, es decir, la suma de 1, 2 y 5</li>
<li><b>-(+(3)(4))(+(-2)(4))</b> daría 5, es decir, la resta entre la suma de 3 y
4, y la suma de -2 y 4
</li>
<li><b>-(+(3)(4))(-(+(5)(6))(4))</b> ...</li>
<li>etc.</li>
</ul>
</div>
