ALTER TABLE ST_User ADD creationDate TIMESTAMP;
ALTER TABLE ST_User ADD saveDate TIMESTAMP;
ALTER TABLE ST_User ADD version INT DEFAULT 0 NOT NULL;
ALTER TABLE ST_User ADD tosAcceptanceDate TIMESTAMP;
ALTER TABLE ST_User ADD lastLoginDate TIMESTAMP;
ALTER TABLE ST_User ADD nbSuccessfulLoginAttempts INT DEFAULT 0 NOT NULL;
ALTER TABLE ST_User ADD lastLoginCredentialUpdateDate TIMESTAMP;
ALTER TABLE ST_User ADD expirationDate TIMESTAMP;
ALTER TABLE ST_User ADD state VARCHAR(30);
ALTER TABLE ST_User ADD stateSaveDate TIMESTAMP;

UPDATE ST_User
SET
  state = (CASE WHEN accessLevel = 'R' THEN 'DELETED'
           ELSE 'VALID' END),
  stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_User MODIFY state NOT NULL;
ALTER TABLE ST_User MODIFY stateSaveDate  NOT NULL;