#
# Copyright (C) 2000 - 2026 Silverpeas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
ApplicationURL=/silverpeas/

# working directory for components (created with the instanciators)
uploadsPath=${project.build.directory}/temp/uploads
# working directory for the search engine
uploadsIndexPath=${project.build.directory}/temp/index
removeLocksOnInit=yes
# working directory for temporaries files
tempPath=${project.build.directory}/temp/temp
# security directory
securityPath = ${project.build.directory}/temp/security

sessionTimeout = /admin/jsp/SessionTimeout.jsp
accessForbidden = /admin/jsp/accessForbidden.jsp
redirectAppInMaintenance = /admin/jsp/appInMaintenance.jsp

RepositoryTypeTemp=Temp

# logo to print in login page and top banner
logo=/admin/jsp/icons/logo_silverpeasBig.gif
smallLogo=/admin/jsp/icons/logo_silverpeas.gif
smallLogoSilverBlue=icons/DomainbarSilverblue/logo.gif

advancedSearchWithPDC = true
domainVisibility = 0
httpServerBase =
