<div id="footer">
	$if(delay)$
		Vous recevrez $delay$ une nouvelle synthèse de notifications.<br/>
		Vous pouvez à tout moment changer la fréquence de réception de cette synthèse depuis le paramétrage de <b>"Mes notifications"</b> accessible depuis votre <b>espace personnel</b>.
	$else$
		Vous avez choisi de ne plus recevoir de synthèse de notifications.<br/>
		Si vous le souhaitez, vous pouvez de nouveau recevoir cette synthèse via le paramétrage de <b>"Mes notifications"</b> accessible depuis votre <b>espace personnel</b>.
	$endif$
</div>