<div id="footer">
	$if(delay)$
		You will receive $delay$ a new notification synthesis.<br/>
		You can change whenever you want the receive frequency of this notification synthesis from the settings of <b>"My notifications"</b> from your <b>personnal space</b>.
	$else$
		You have chosen to stop receiving notification synthesis.<br/>
		If you wish, you can again receive this synthesis from the settings of <b>"My notifications"</b> accessible from your <b>personal space</b>.
	$endif$
</div>