<div id="footer">
$if(delay)$
You will receive $delay$ a new notification synthesis.<br/>
You can change whenever you want the receive frequency of this notification synthesis from the settings of "My notifications" from your personnal space.
$else$
You have chosen to stop receiving notification synthesis.<br/>
If you wish, you can again receive this synthesis from the settings of "My notifications" accessible from your personal space.
$endif$
</div>