/*
 * Copyright (C) 2000 - 2026 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */
package org.silverpeas.core.security.authentication.twofactor.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.silverpeas.core.security.authentication.twofactor.model.RecoveryCode;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.empty;
import static org.hamcrest.Matchers.is;

class RecoveryCodeRepositoryTest {

    private static final int USER_ID = 42;
    private static final int OTHER_USER_ID = 43;
    private static final String HASH = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
    private static final String OTHER_HASH =
            "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789";
    private static final String JDBC_URL =
            "jdbc:h2:mem:recovery_code_repository;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";

    private final RecoveryCodeRepositoryImpl repository = new RecoveryCodeRepositoryImpl();

    @BeforeEach
    void setUp() throws SQLException {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS ST_User_2FA_Recovery (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "userId INT NOT NULL, hash VARCHAR(64) NOT NULL, " +
                    "used BOOLEAN NOT NULL DEFAULT FALSE, createdAt TIMESTAMP NOT NULL, " +
                    "usedAt TIMESTAMP)");
            statement.executeUpdate("DELETE FROM ST_User_2FA_Recovery");
        }
    }

    @Test
    void shouldReturnOnlyUnusedCodesOfUser() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");
        Instant usedAt = Instant.parse("2026-09-23T09:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection, recoveryCode(USER_ID, HASH, false, createdAt, null));
            repository.save(connection, recoveryCode(USER_ID, OTHER_HASH, true, createdAt, usedAt));
            repository.save(connection, recoveryCode(OTHER_USER_ID, HASH, false, createdAt, null));

            List<RecoveryCode> codes = repository.getUnused(connection, USER_ID);

            assertThat(codes.size(), is(1));
            assertThat(codes.get(0).getUserId(), is(USER_ID));
            assertThat(codes.get(0).getHash(), is(HASH));
            assertThat(codes.get(0).isUsed(), is(false));
            assertThat(codes.get(0).getCreatedAt(), is(createdAt));
            assertThat(codes.get(0).getUsedAt(), is((Instant) null));
        }
    }

    @Test
    void shouldReturnEmptyWhenUserHasNoUnusedCodes() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection, recoveryCode(USER_ID, HASH, true, createdAt, createdAt));

            assertThat(repository.getUnused(connection, USER_ID), is(empty()));
        }
    }

    @Test
    void shouldSaveRecoveryCode() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection, recoveryCode(USER_ID, HASH, false, createdAt, null));

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(
                         "SELECT userId, hash, used, createdAt, usedAt " +
                                 "FROM ST_User_2FA_Recovery WHERE userId = " + USER_ID)) {
                assertThat(resultSet.next(), is(true));
                assertThat(resultSet.getInt("userId"), is(USER_ID));
                assertThat(resultSet.getString("hash"), is(HASH));
                assertThat(resultSet.getBoolean("used"), is(false));
                assertThat(resultSet.getTimestamp("createdAt").toInstant(), is(createdAt));
                assertThat(resultSet.getTimestamp("usedAt"), is((java.sql.Timestamp) null));
            }
        }
    }

    @Test
    void shouldConsumeUnusedRecoveryCode() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");
        Instant usedAt = Instant.parse("2026-09-23T09:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection, recoveryCode(USER_ID, HASH, false, createdAt, null));

            assertThat(repository.consume(connection, HASH, usedAt), is(true));

            List<RecoveryCode> codes = repository.getUnused(connection, USER_ID);
            assertThat(codes, is(empty()));

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(
                         "SELECT used, usedAt FROM ST_User_2FA_Recovery WHERE hash = '" + HASH + "'")) {
                assertThat(resultSet.next(), is(true));
                assertThat(resultSet.getBoolean("used"), is(true));
                assertThat(resultSet.getTimestamp("usedAt").toInstant(), is(usedAt));
            }
        }
    }

    @Test
    void shouldNotConsumeAlreadyUsedRecoveryCode() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");
        Instant originalUsedAt = Instant.parse("2026-09-23T09:00:00Z");
        Instant attemptedUsedAt = Instant.parse("2026-09-23T10:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection,
                    recoveryCode(USER_ID, HASH, true, createdAt, originalUsedAt));

            assertThat(repository.consume(connection, HASH, attemptedUsedAt), is(false));

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(
                         "SELECT usedAt FROM ST_User_2FA_Recovery WHERE hash = '" + HASH + "'")) {
                assertThat(resultSet.next(), is(true));
                assertThat(resultSet.getTimestamp("usedAt").toInstant(), is(originalUsedAt));
            }
        }
    }

    @Test
    void shouldNotConsumeUnknownRecoveryCode() throws SQLException {
        Instant usedAt = Instant.parse("2026-09-23T09:00:00Z");

        try (Connection connection = connection()) {
            assertThat(repository.consume(connection, HASH, usedAt), is(false));
        }
    }

    @Test
    void shouldDeleteAllRecoveryCodesOfUser() throws SQLException {
        Instant createdAt = Instant.parse("2026-09-23T08:00:00Z");

        try (Connection connection = connection()) {
            repository.save(connection, recoveryCode(USER_ID, HASH, false, createdAt, null));
            repository.save(connection, recoveryCode(USER_ID, OTHER_HASH, false, createdAt, null));
            repository.save(connection, recoveryCode(OTHER_USER_ID, HASH, false, createdAt, null));

            repository.deleteAll(connection, USER_ID);

            assertThat(repository.getUnused(connection, USER_ID), is(empty()));
            assertThat(repository.getUnused(connection, OTHER_USER_ID),
                    contains(org.hamcrest.Matchers.hasProperty("hash", is(HASH))));
        }
    }

    private Connection connection() throws SQLException {
        return DriverManager.getConnection(JDBC_URL);
    }

    private RecoveryCode recoveryCode(int userId, String hash, boolean used,
                                      Instant createdAt, Instant usedAt) {
        return RecoveryCode.builder(userId)
                .hash(hash)
                .used(used)
                .createdAt(createdAt)
                .usedAt(usedAt)
                .build();
    }
}
