Bonjour $fullName$,

Merci de vous &ecirc;tre enregistr&eacute; sur Silverpeas.
En plus de pouvoir vous connecter depuis votre r&eacute;seau social pr&eacute;f&eacute;r&eacute;, vous avez &eacute;galement la possibilit&eacute;
de vous identifier avec les codes suivants :

<b>Identifiant : </b>$login$
<b>Mot de passe : </b>$password$
$if(domain)$
<b>Domaine : </b>$domain.name$
$endif$


Pour vous connecter, cliquez <a href="$url$">ici</a>