<b>$senderUser.firstName$ $senderUser.lastName$</b> хотів би запросити вас приєднатися до його контактів.

$if(senderMessage)$
Повідомлення :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

Щоб прийняти це запрошення, перейдіть у свій особистий кабінет у розділі «Мій профіль».
Потім перейдіть на вкладку «Запрошення» та прийміть або проігноруйте це запрошення.
