<b>$senderUser.firstName$ $senderUser.lastName$</b> wants to add you in his contacts.

$if(senderMessage)$
Message :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

In order to accept this invitation, please connect to your personnal account.
You have to go on your profil on the Invitations tab. Then you can use accept or ignore link.