<b>$senderUser.firstName$ $senderUser.lastName$</b> souhaite vous inviter à rejoindre ses contacts.

$if(senderMessage)$
Message :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

Pour accepter cette invitation, veuillez vous rendre dans votre espace personnel sur la partie "Mon profil".
Veuillez ensuite vous rendre sur l'onglet "Invitations" puis accepter ou ignorer cette invitation.