<b>$senderUser.firstName$ $senderUser.lastName$</b> le gustaría invitarle a unirse a sus contactos.

$if(senderMessage)$
Mensaje :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

Para aceptar esta invitación, acceda a su espacio personal en la sección &quot;Mi perfil&quot;.
Luego, vaya a la pestaña &quot;Invitaciones&quot; y acepte o ignore esta invitación.
