<b>$senderUser.firstName$ $senderUser.lastName$</b> хотел бы пригласить вас присоединиться к своим контактам.

$if(senderMessage)$
Сообщение :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

Чтобы принять это приглашение, перейдите в свой личный кабинет в раздел «Мой профиль».
Затем перейдите на вкладку «Приглашения» и примите или отклоните это приглашение.
