<b>$senderUser.firstName$ $senderUser.lastName$</b> möchte Sie in seinen Kontakten hinzufügen.

$if(senderMessage)$
Nachricht :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;">$senderMessage$</div>
$endif$

Um diese Einladung anzunehmen, wenden Sie sich bitte an Ihren personnal verändern.
Sie haben auf Ihrem Profil auf der Registerkarte Einladungen gehen. Dann können Sie annehmen oder ignorieren Link.