CREATE TABLE ST_User_2FA (
  userId INTEGER NOT NULL PRIMARY KEY,
  secret VARCHAR(2048) NOT NULL,
  status VARCHAR(20) NOT NULL,
  createdAt TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP NOT NULL,
  lastUsedAt TIMESTAMP NULL,
  failedAttempts INTEGER NOT NULL DEFAULT 0,
  lockedUntil TIMESTAMP NULL
);
