/*
 * Copyright (C) 2000 - 2016 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * As a special exception to the terms and conditions of version 3.0 of
 * the GPL, you may redistribute this Program in connection with Free/Libre
 * Open Source Software ("FLOSS") applications as described in Silverpeas's
 * FLOSS exception.  You should have received a copy of the text describing
 * the FLOSS exception, and it is also available here:
 * "http://www.silverpeas.org/docs/core/legal/floss_exception.html"
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.02.14 at 03:42:33 PM CET
//

package org.silverpeas.core.admin.space.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.silverpeas.core.admin.space.model package.
 * <p>
 * An ObjectFactory allows you to programmatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _SpaceTemplate_QNAME =
      new QName("http://silverpeas.org/xml/ns/space", "SpaceTemplate");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.silverpeas.admin.spaces
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link SpaceComponentParameter }
   */
  public SpaceComponentParameter createSpaceComponentParameter() {
    return new SpaceComponentParameter();
  }

  /**
   * Create an instance of {@link SpaceComponent }
   */
  public SpaceComponent createSpaceComponent() {
    return new SpaceComponent();
  }

  /**
   * Create an instance of {@link SpaceTemplate }
   */
  public SpaceTemplate createSpaceTemplate() {
    return new SpaceTemplate();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SpaceTemplate }{@code >}
   */
  @XmlElementDecl(namespace = "http://silverpeas.org/xml/ns/space", name = "SpaceTemplate")
  public JAXBElement<SpaceTemplate> createSpaceTemplate(SpaceTemplate value) {
    return new JAXBElement<SpaceTemplate>(_SpaceTemplate_QNAME, SpaceTemplate.class, null, value);
  }

}
