/*
 * Copyright (C) 2000 - 2016 Silverpeas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * As a special exception to the terms and conditions of version 3.0 of
 * the GPL, you may redistribute this Program in connection with Free/Libre
 * Open Source Software ("FLOSS") applications as described in Silverpeas's
 * FLOSS exception.  You should have received a copy of the text describing
 * the FLOSS exception, and it is also available here:
 * "http://www.silverpeas.org/docs/core/legal/floss_exception.html"
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.02.14 at 03:42:33 PM CET
//
package org.silverpeas.core.admin.space.model;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SpaceTemplateType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name=&quot;SpaceTemplateType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;template&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;defaultName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;readonly&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *         &lt;element name=&quot;components&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name=&quot;component&quot; type=&quot;{http://silverpeas.org/xml/ns/space}ComponentType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpaceTemplateType", propOrder = { "template", "defaultName", "description",
    "readonly", "components" })
public class SpaceTemplate {

  @XmlElement(required = true)
  protected String template;
  @XmlElement(required = true)
  protected String defaultName;
  @XmlElement(required = true)
  protected String description;
  protected boolean readonly;
  @XmlElementWrapper(name = "components")
  @XmlElement(name = "component")
  protected List<SpaceComponent> components;

  /**
   * Gets the value of the template property.
   * @return possible object is {@link String }
   */
  public String getTemplate() {
    return template;
  }

  /**
   * Sets the value of the template property.
   * @param value allowed object is {@link String }
   */
  public void setTemplate(String value) {
    this.template = value;
  }

  /**
   * Gets the value of the defaultName property.
   * @return possible object is {@link String }
   */
  public String getDefaultName() {
    return defaultName;
  }

  /**
   * Sets the value of the defaultName property.
   * @param value allowed object is {@link String }
   */
  public void setDefaultName(String value) {
    this.defaultName = value;
  }

  /**
   * Gets the value of the description property.
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the readonly property.
   */
  public boolean isReadonly() {
    return readonly;
  }

  /**
   * Sets the value of the readonly property.
   */
  public void setReadonly(boolean value) {
    this.readonly = value;
  }

  /**
   * Gets the value of the components property.
   * @return possible object is {@link SpaceComponent }
   */
  public List<SpaceComponent> getComponents() {
    return components;
  }

  /**
   * Sets the value of the components property.
   * @param value allowed object is {@link SpaceComponent }
   */
  public void setComponents(List<SpaceComponent> value) {
    this.components = value;
  }
}
