CREATE TABLE ST_User_2FA
(
    userId     INT           NOT NULL,
    secret     VARCHAR2(1024) NOT NULL,
    status     VARCHAR2(20)  NOT NULL,
    createdAt  TIMESTAMP     NOT NULL,
    updatedAt  TIMESTAMP     NOT NULL,
    lastUsedAt TIMESTAMP,
    failedAttempts INT NOT NULL DEFAULT 0,
    lockedUntil TIMESTAMP
);

CREATE TABLE ST_User_2FA_Recovery
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId NUMBER(10) NOT NULL,
    hash VARCHAR2(64) NOT NULL,
    used NUMBER(1) NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    usedAt TIMESTAMP
);