DROP INDEX SR_UNINSTITEMS.R_24_FK;

DROP INDEX SR_UNINSTITEMS.SR_UNINSTITEMS_I1;

DROP INDEX SR_SCRIPTS.RELATION_46_FK;

DROP INDEX SR_DEPENDENCIES.IN_DEPENDENCIES_1;

ALTER TABLE SR_UNINSTITEMS DROP CONSTRAINT PK_SR_UNINSTITEMS;

DROP TABLE SR_RELLOG2;

DROP TABLE SR_UNINSTITEMS;

DROP TABLE SR_SCRIPTS;

DROP TABLE SR_DEPENDENCIES;