drop index SR_SCRIPTS.RELATION_46_FK;
drop index SR_SCRIPTS.SR_SCRIPTS_I1;
drop index SR_UNINSTITEMS.R_24_FK;
drop index SR_UNINSTITEMS.SR_UNINSTITEMS_I1;
drop index SR_DEPENDENCIES.IN_DEPENDENCIES_1;