ALTER TABLE ST_Group ADD creationDate DATETIME;
ALTER TABLE ST_Group ADD saveDate DATETIME;
ALTER TABLE ST_Group ADD state VARCHAR(30);
ALTER TABLE ST_Group ADD stateSaveDate DATETIME;

UPDATE ST_Group
SET
    state = 'VALID',
    stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_Group ALTER COLUMN state VARCHAR(30) NOT NULL;
ALTER TABLE ST_Group ALTER COLUMN stateSaveDate DATETIME NOT NULL;