UPDATE ST_Group
SET
    state = 'VALID',
    stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_Group ALTER COLUMN state VARCHAR(30) NOT NULL;
ALTER TABLE ST_Group ALTER COLUMN stateSaveDate DATETIME NOT NULL;