<p><b>Saisissez directement</b> votre recherche.<br/><img src="/silverpeas/directory/jsp/images/recherche.png" alt="" /><br/>
		Attention! Elle porte sur le nom et le pr&eacute;nom de la personne que vous recherchez mais &eacute;galement sur les autres informations : fonction, service, sup&eacute;rieur, adresse...</p>
	<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
	<p>   <b><span style="color:#f1790f;">ou</span> afficher par ordre alphab&eacute;tique</b> du nom de famille <img style="float:right"src="/silverpeas/directory/jsp/images/alphabet.png" alt="" /><br/> </p>
	<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
	<p>  <b><span style="color:#f1790f;">ou</span> filtrer par statut</b> <img style="float:right"src="/silverpeas/directory/jsp/images/connectes.png" alt="" /><br/>
</p>