<p><b>Enter your search directly</b> in the appropriate field.<br/><img src="/silverpeas/directory/jsp/images/recherche.png" alt="" /><br/>
		Attention! It covers the name and surname of the person you are looking for but also other information: function, service, address ...</p>
	<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
	<p>   <b><span style="color:#f1790f;">or</span> display alphabetically</b> by name <img style="float:right"src="/silverpeas/directory/jsp/images/alphabet.png" alt="" /><br/> </p>
	<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
	<p>  <b><span style="color:#f1790f;">or</span> filter by state</b> <img style="float:right"src="/silverpeas/directory/jsp/images/connectes.png" alt="" /><br/>
</p>