<p><b>Введите ваш поиск напрямую</b> .<br/><img src="/silverpeas/directory/jsp/images/recherche.png" alt="" /><br/>
Внимание! Это относится к фамилии и имени человека, которого вы ищете, а также к другой информации: функции, отделу, начальнику, адресу и т. д.</p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">или</span> просмотреть в алфавитном порядке</b> по фамилии <img style="float:right"src="/silverpeas/directory/jsp/images/alphabet.png" alt="" /><br/></p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">или</span> фильтровать по статусу</b><img style="float:right"src="/silverpeas/directory/jsp/images/connectes.png" alt="" /><br/>
</p>
