//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.18 at 04:04:03 PM CET 
//
package com.silverpeas.admin.components;

import java.util.HashMap;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for ParameterOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterOptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterOptionType", propOrder = {
  "name",
  "value"
})
public class Option {

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(MultilangHashMapAdapter.class)
  protected HashMap<String, String> name;
  @XmlElement(required = true)
  protected String value;

  /**
   * Gets the value of the name property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public HashMap<String, String> getName() {
    if(name == null) {
      name = new HashMap<String, String>();
    }
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setName(HashMap<String, String> value) {
    this.name = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setValue(String value) {
    this.value = value;
  }
  
  @Override
  @SuppressWarnings({"unchecked"})
  public Option clone() {
    Option option = new Option();
    option.setName((HashMap<String, String>)getName().clone());
    option.setValue(value);
    return option;
  }
}
