//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.14 at 04:45:31 PM CET 
//
package com.silverpeas.admin.components;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for WAComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WAComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="description" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="suite" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="visibleInPersonalSpace" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="portlet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="instanceClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="profile" type="{http://silverpeas.org/xml/ns/component}ProfileType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="parameters" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameter" type="{http://silverpeas.org/xml/ns/component}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WAComponentType", propOrder = {
  "name",
  "label",
  "description",
  "suite",
  "visible",
  "visibleInPersonalSpace",
  "portlet",
  "router",
  "instanceClassName",
  "profiles",
  "parameters"
})
public class WAComponent {

  @XmlElement(required = true)
  protected String name;
  @XmlElement(required = false)
  protected String router;
  @XmlElement(required = true)
  protected Multilang label;
  @XmlElement(required = true)
  protected Multilang description;
  @XmlElement(required = true)
  protected Multilang suite;
  protected boolean visible;
  protected Boolean visibleInPersonalSpace;
  protected boolean portlet;
  @XmlElement(required = true)
  protected String instanceClassName;
  @XmlElement(required = true)
  protected List<Profile> profiles;
  protected List<Parameter> parameters;

  /**
   * Gets the value of the name property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the label property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public Multilang getLabel() {
    return label;
  }

  /**
   * Sets the value of the label property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setLabel(Multilang value) {
    this.label = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public Multilang getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setDescription(Multilang value) {
    this.description = value;
  }

  /**
   * Gets the value of the suite property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public Multilang getSuite() {
    return suite;
  }

  /**
   * Sets the value of the suite property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setSuite(Multilang value) {
    this.suite = value;
  }

  /**
   * Gets the value of the visible property.
   * 
   */
  public boolean isVisible() {
    return visible;
  }

  /**
   * Sets the value of the visible property.
   * 
   */
  public void setVisible(boolean value) {
    this.visible = value;
  }

  /**
   * Gets the value of the visibleInPersonalSpace property.
   * 
   * @return
   *     possible object is
   *     {@link Boolean }
   *     
   */
  public Boolean isVisibleInPersonalSpace() {
    return visibleInPersonalSpace;
  }

  /**
   * Sets the value of the visibleInPersonalSpace property.
   * 
   * @param value
   *     allowed object is
   *     {@link Boolean }
   *     
   */
  public void setVisibleInPersonalSpace(Boolean value) {
    this.visibleInPersonalSpace = value;
  }

  /**
   * Gets the value of the portlet property.
   * 
   */
  public boolean isPortlet() {
    return portlet;
  }

  /**
   * Sets the value of the portlet property.
   * 
   */
  public void setPortlet(boolean value) {
    this.portlet = value;
  }

  /**
   * Gets the value of the instanceClassName property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getInstanceClassName() {
    return instanceClassName;
  }

  /**
   * Sets the value of the instanceClassName property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setInstanceClassName(String value) {
    this.instanceClassName = value;
  }

  /**
   * Gets the value of the profiles property.
   * 
   * @return
   *     possible object is
   *     {@link Profile }
   *     
   */
  public List<Profile> getProfiles() {
    return profiles;
  }

  /**
   * Sets the value of the profiles property.
   * 
   * @param value
   *     allowed object is
   *     {@link Profile }
   *     
   */
  public void setProfiles(List<Profile> value) {
    this.profiles = value;
  }

  /**
   * Gets the value of the parameters property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the parameters property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getParameters().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Parameter }
   * 
   * 
   */
  public List<Parameter> getParameters() {
    if (parameters == null) {
      parameters = new ArrayList<Parameter>();
    }
    return this.parameters;
  }

  /**
   * Sets the value of the profiles property.
   *
   * @param value
   *     allowed object is
   *     {@link Profile }
   *
   */
  public void setParameters(List<Parameter> value) {
    this.parameters = value;
  }

  public String getRouter() {
    return router;
  }

  public void setRouter(String router) {
    this.router = router;
  }
}
