//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.18 at 04:04:03 PM CET 
//
package com.silverpeas.admin.components;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for WAComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WAComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="description" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="suite" type="{http://silverpeas.org/xml/ns/component}multilang"/>
 *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="visibleInPersonalSpace" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="portlet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="router" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instanceClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="profile" type="{http://silverpeas.org/xml/ns/component}ProfileType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="parameters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameter" type="{http://silverpeas.org/xml/ns/component}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WAComponentType", propOrder = {
  "name",
  "label",
  "description",
  "suite",
  "visible",
  "visibleInPersonalSpace",
  "portlet",
  "router",
  "instanceClassName",
  "profiles",
  "parameters"
})
public class WAComponent {
  @XmlTransient
  private ParameterSorter sorter = new ParameterSorter();

  @XmlElement(required = true)
  protected String name;
  @XmlElement(required = true)
  @XmlJavaTypeAdapter(MultilangHashMapAdapter.class)
  protected HashMap<String, String> label;
  @XmlElement(required = true)
  @XmlJavaTypeAdapter(MultilangHashMapAdapter.class)
  protected HashMap<String, String> description;
  @XmlElement(required = true)
  @XmlJavaTypeAdapter(MultilangHashMapAdapter.class)
  protected HashMap<String, String> suite;
  protected boolean visible;
  protected boolean visibleInPersonalSpace = false;
  protected boolean portlet;
  protected String router;
  @XmlElement(required = true)
  protected String instanceClassName;
  @XmlElementWrapper(name="profiles")
  @XmlElement(name="profile", required = true) 
  protected List<Profile> profiles;
  @XmlElementWrapper(name="parameters")
  @XmlElement(name="parameter") 
  protected List<Parameter> parameters;

  /**
   * Gets the value of the name property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the label property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public HashMap<String, String> getLabel() {
    if(label == null){
      label = new HashMap<String, String>();
    }
    return label;
  }

  /**
   * Sets the value of the label property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setLabel(HashMap<String, String> value) {
    this.label = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public HashMap<String, String> getDescription() {
    if(description == null){
      description = new HashMap<String, String>();
    }
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setDescription(HashMap<String, String> value) {
    this.description = value;
  }

  /**
   * Gets the value of the suite property.
   * 
   * @return
   *     possible object is
   *     {@link Multilang }
   *     
   */
  public HashMap<String, String> getSuite() {
    if(suite == null){
      suite = new HashMap<String, String>();
    }
    return suite;
  }

  /**
   * Sets the value of the suite property.
   * 
   * @param value
   *     allowed object is
   *     {@link Multilang }
   *     
   */
  public void setSuite(HashMap<String, String> value) {
    this.suite = value;
  }

  /**
   * Gets the value of the visible property.
   * 
   */
  public boolean isVisible() {
    return visible;
  }

  /**
   * Sets the value of the visible property.
   * 
   */
  public void setVisible(boolean value) {
    this.visible = value;
  }

  /**
   * Gets the value of the visibleInPersonalSpace property.
   * 
   * @return
   *     possible object is
   *     {@link Boolean }
   *     
   */
  public boolean isVisibleInPersonalSpace() {
    return visibleInPersonalSpace;
  }

  /**
   * Sets the value of the visibleInPersonalSpace property.
   * 
   * @param value
   *     allowed object is
   *     {@link Boolean }
   *     
   */
  public void setVisibleInPersonalSpace(boolean value) {
    this.visibleInPersonalSpace = value;
  }

  /**
   * Gets the value of the portlet property.
   * 
   */
  public boolean isPortlet() {
    return portlet;
  }

  /**
   * Sets the value of the portlet property.
   * 
   */
  public void setPortlet(boolean value) {
    this.portlet = value;
  }

  /**
   * Gets the value of the router property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getRouter() {
    return router;
  }

  /**
   * Sets the value of the router property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setRouter(String value) {
    this.router = value;
  }

  /**
   * Gets the value of the instanceClassName property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getInstanceClassName() {
    return instanceClassName;
  }

  /**
   * Sets the value of the instanceClassName property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setInstanceClassName(String value) {
    this.instanceClassName = value;
  }

  /**
   * Gets the value of the profiles property.
   * 
   * @return
   *     possible object is
   *     {@link WAComponent.Profiles }
   *     
   */
  public List<Profile> getProfiles() {
    if(profiles == null){
      profiles = new ArrayList<Profile>();
    }
    return profiles;
  }
  
  public Profile getProfile(String name) {
    for (Profile profile : getProfiles()) {
      if (profile.getName().equals(name)) {
        return profile;
      }
    }
    return null;
  }

  /**
   * Sets the value of the profiles property.
   * 
   * @param value
   *     allowed object is
   *     {@link WAComponent.Profiles }
   *     
   */
  public void setProfiles(List<Profile> value) {
    this.profiles = value;
  }

  /**
   * Gets the value of the parameters property.
   * 
   * @return
   *     possible object is
   *     {@link WAComponent.Parameters }
   *     
   */
  public List<Parameter> getParameters() {
    if(parameters == null){
      parameters = new ArrayList<Parameter>();
    }
    return parameters;
  }

  /**
   * Sets the value of the parameters property.
   * 
   * @param value
   *     allowed object is
   *     {@link WAComponent.Parameters }
   *     
   */
  public void setParameters(List<Parameter> value) {
    this.parameters = value;
  }
  
  public List<Parameter> getSortedParameters() {
    Collections.sort(getParameters(), sorter);
    return this.parameters;
  }
  
  public List<Parameter> cloneParameters()  {
    List<Parameter> result = new ArrayList<Parameter>(getParameters().size());
    for(Parameter param : getParameters()){
      result.add(param.clone());
    }
    Collections.sort(result, sorter);
    return result;
  }
}
