$if(several)$
$senderName$ a modifié votre status de présence pour les événements <b>$contributionName$</b>$if(contributionStartDate)$ à partir du <i>$contributionStartDate$</i>$endif$
$else$
$senderName$ a modifié votre status de présence pour l'événement <b>$contributionName$</b>$if(contributionStartDate)$ du <i>$contributionStartDate$</i>$if(contributionEndDate)$ jusqu'au <i>$contributionEndDate$</i>$endif$$endif$
$endif$