<h2 class="txtNav"><center>Bienvenido a la gestión de espacios y aplicaciones</center></h2>

<p class="accroche">Silverpeas se estructura en espacios que contienen aplicaciones. Cada espacio también puede contener subespacios.<br/>
Se ofrece una amplia variedad de aplicaciones listas para usar para satisfacer todas sus necesidades: gestión de documentos, galería de imágenes, blog, encuestas, gestión de proyectos...<br/>
Como <b>administrador de la plataforma</b> , puedes gestionar todos los espacios y aplicaciones en cualquier momento.</p>

<div id="txt_evolutivite">
<h3>¡Cambiar la estructura de tu plataforma es un juego de niños!</h3>
<p>Puede crear rápidamente un espacio de nivel superior <a class="txtnav" href="CreateSpace">haciendo clic aquí</a> o eligiendo la operación <b class="yuimenu">Crear espacio</b> en el menú <b>¿Qué desea hacer?.</b> .</p>
<p>Se puede acceder a todos los espacios de nivel superior desde la lista desplegable de la izquierda. Para modificar, eliminar o enriquecer un espacio, simplemente selecciónelo de esta lista.<br />
El contenido del espacio seleccionado aparece debajo de esta lista desplegable. Todas las operaciones disponibles en el espacio seleccionado son accesibles a través del menú <b>¿Qué quieres hacer?</b> .<br/>
En particular, puede:</p>
<ul>
<li>agregar, modificar, eliminar aplicaciones,</li>
<li>definir los derechos de acceso que se aplican a estas aplicaciones,</li>
<li>delegar su gestión a cualquier usuario,</li>
<li>definir una página de inicio específica,</li>
<li>...</li>
</ul>
<p>Para modificar un subespacio o una aplicación, seleccionarlo le dará acceso a todas sus operaciones, nuevamente usando el <b>botón ¿Qué quieres hacer?</b> .</p>
</div>

<div id="txt_restauration">
<h3>¡Uf... el contenedor de espacios y aplicaciones está aquí!</h3>
<p>Para evitar daños causados por un manejo inadecuado, los espacios y las aplicaciones no se eliminan de forma permanente.<br/>
Antes de su borrado definitivo, se pueden restaurar a través de la papelera haciendo <a class="txtnav" href="ViewBin">clic aquí</a> o eligiendo la <b class="yuimenu">operación Papelera de espacios y aplicaciones</b> del menú <b>¿Qué quieres hacer?</b> .<br/>
Esta cesta está reservada para los administradores. Por lo tanto, usted es el único que puede restaurar y eliminar permanentemente espacios o aplicaciones.<br/>
Cabe señalar que durante la restauración se deben volver a definir los derechos específicos.</p>
</div>

<div id="txt_maintenance">
<h3>Modo de mantenimiento</h3>
<p>Este modo permite que la plataforma no esté disponible temporalmente.
Útil durante cambios importantes, solo los administradores podrán acceder a la plataforma y su contenido.<br/>
Este modo también está disponible a nivel de cada espacio a través de la operación <b class="yuimenu">Activar modo mantenimiento</b> en el menú <b>¿Qué quieres hacer?</b> .<br /> En este caso, un mensaje advierte a los usuarios de la indisponibilidad temporal.</p>
</div>
