<h2 class="txtNav"><center>Bienvenido a la gestión de espacios y aplicaciones</center></h2>

<p class="accroche">Silverpeas se estructura en espacios que contienen aplicaciones. Cada espacio también puede contener subespacios.<br/>
Se ofrece una amplia variedad de aplicaciones listas para usar para satisfacer todas sus necesidades: gestión de documentos, galería de imágenes, blog, encuestas, gestión de proyectos...<br/>
Como <b>gestor de espacio(s)</b> , puedes gestionar libremente todos los espacios de los que eres responsable.</p>

<div id="txt_evolutivite">
<h3>¡Cambiar la estructura de tu espacio es un juego de niños!</h3>
<p>Se puede acceder a todos los espacios de nivel superior desde la lista desplegable de la izquierda. Para modificar, eliminar o enriquecer un espacio, simplemente selecciónelo de esta lista.<br/>
El contenido del espacio seleccionado aparece debajo de esta lista desplegable.
Todas las operaciones disponibles en este espacio son accesibles a través del menú <b>¿Qué quieres hacer?</b> .<br/>
En particular, puede:</p>
<ul>
<li>agregar, modificar, eliminar aplicaciones,</li>
<li>definir los derechos de acceso que se aplican a estas aplicaciones,</li>
<li>delegar su gestión a cualquier usuario,</li>
<li>definir una página de inicio específica,</li>
<li>...</li>
</ul>
<p>Para administrar un subespacio o una aplicación, seleccionarlo le permitirá acceder a todas sus operaciones, nuevamente utilizando el <b>¿Qué desea hacer?</b> .</p>
</div>
