<h2 class="txtNav"><center>Welcome to spaces and applications management</center></h2>

<p class="accroche">Silverpeas is structured into spaces that contain applications. Each space may also contains sub-spaces.<br/>
A wide range of applications ready to use is offered to meet all your needs : document management, image gallery, blog, surveys, project management...<br/>
As a <b>space(s) manager</b>, you can manage all the spaces you care.</p>

<div id="txt_evolutivite">
<h3>It's very easy to change the structure of your space !</h3>
<p>All first-level spaces are accessible in the drop-down list on the left. To edit, delete or manage a space, simply select it from this list.<br/>
The content of the selected space will then appear in this list.
All the operations available on this space are accessible via the menu <b>What&nbsp;do&nbsp;you&nbsp;want&nbsp;to&nbsp;do&nbsp;next?</b>.<br/>
You can especially :</p>
<ul>
<li>add, edit or remove applications,</li>
<li>define the access rights that apply to those applications,</li>
<li>delegate its management to any user,</li>
<li>define a specific home page,</li>
<li>...</li>
</ul>
<p>To manage a subspace or application, click on their name. It will give you access to all its operations, using the menu <b>What&nbsp;do&nbsp;you&nbsp;want&nbsp;to&nbsp;do&nbsp;next?</b>.</p>
</div>