<h2 class="txtNav"><center>Willkommen bei der Verwaltung von Bereiche und Anwendungen</center></h2>

<p class="accroche">Silverpeas wird in Bereiche, die Anwendungen enthalten strukturiert. Jeder Bereich kann auch Unterbereiche enthalten.<br/>
$if(communityEnabled)$
Neben den Bereiche ist es möglich, Communities zu erstellen. Dabei handelt es sich um besondere Bereiche, denen die Nutzer selbst beitreten möchten, anstatt dass ihnen ein Administrator den Zugang gewährt.
<br/>
$endif$
Eine breite Palette an einsatzbereiten Anwendungen steht zur Verfügung, um all Ihren Anforderungen gerecht zu werden: Dokumentenmanagement, Bildergalerie, Blog, Umfragen, Projektmanagement...<br/>
Als <b>Administrator</b> können Sie alle Bereiche und Anwendungen verwalten.</p>

<div id="txt_evolutivite">
<h3>Es ist sehr einfach, die Struktur Ihrer Plattform zu ändern!</h3>
<p>Sie können schnell einen Bereich der ersten Ebene erstellen, indem Sie <a class="txtnav" href="CreateSpace">hier klicken</a> oder im Menü <b>Was möchten Sie tun?</b> den Befehl <b class="yuimenu">Bereich erstellen </b>auswählen.</b>.<br/>
</p><p>Alle Bereiche der ersten Ebene sind in der Dropdown-Liste auf der linken Seite zugänglich. Um einen Bereich zu ändern, zu löschen oder zu ergänzen, wählen Sie ihn einfach aus dieser Liste aus.<br/>
Der Inhalt des ausgewählten Bereichs wird dann unter dieser Dropdown-Liste angezeigt. Alle für den ausgewählten Bereich verfügbaren Vorgänge sind über das Menü <b>Was möchten Sie tun?</b> zugänglich. Sie können insbesondere:</p>
<ul>
<li>Anwendungen hinzufügen, ändern oder löschen</li>
<li>die für diese Anwendungen geltenden Zugriffsrechte festlegen,</li>
<li>die Verwaltung an beliebige Benutzer delegieren,</li>
<li>eine bestimmte Startseite festlegen,</li>
<li>...</li>
</ul>
<p>Um einen Unterbereich oder eine Anwendung zu ändern, wählen Sie diese aus, um Zugriff auf alle zugehörigen Vorgänge zu erhalten. Auch hierfür steht Ihnen das Menü <b>Was möchten Sie tun?</b> zur Verfügung.</p>
</div>

<div id="txt_restauration">
<h3>Puh... der Papierkorb für Bereiche und Anwendungen ist da!</h3>
<p>Um Schäden durch unsachgemäße Handhabung zu vermeiden, werden Bereiche und Anwendungen nicht endgültig gelöscht.
Vor ihrer endgültigen Löschung können sie über den Papierkorb wiederhergestellt werden, indem Sie hier klicken oder im Menü „Was möchten Sie tun?“ den Befehl „Papierkorb für Bereiche und Anwendungen“ auswählen. </b>.<br/>
Dieser Papierkorb ist Administratoren vorbehalten. Sie sind also die Einzigen, die Bereiche oder Anwendungen wiederherstellen und endgültig löschen können.<br/>
Beachten Sie, dass bei der Wiederherstellung die spezifischen Rechte neu definiert werden müssen.</p>
</div>

<div id="txt_maintenance">
<h3>Der Wartungsmodus</h3>
<p>Dieser Modus ermöglicht es, die Plattform vorübergehend nicht verfügbar zu machen.
Dies ist bei umfangreichen Änderungen nützlich, da nur Administratoren auf die Plattform und ihre Inhalte zugreifen können.<br/>
Dieser Modus ist auch auf Ebene jedes Bereichs über die Option <b class="yuimenu"> Wartungsmodus aktivieren </b> im Menü <b>Was möchten Sie tun?</b> verfügbar. <br />In diesem Fall werden die Benutzer durch eine Meldung über die vorübergehende Nichtverfügbarkeit informiert. </p>
</div>
