<h2 class="txtNav"><center>Bienvenue sur la gestion des espaces et des applications</center></h2>

<p class="accroche">Silverpeas est structuré en espaces qui contiennent des applications. Chaque espace peut également contenir des sous espaces.<br/>
Un large choix d'applications prêtes à l'emploi vous est offert pour répondre à tous vos besoins : gestion documentaire, galerie d'images, blog, sondages, gestion de projet...<br/>
En tant que <b>gestionnaire d'espace(s)</b>, vous pouvez gérer librement l'ensemble des espaces dont vous avez la charge.</p>

<div id="txt_evolutivite">
<h3>Faire évoluer la structure de votre espace est un jeu d'enfant !</h3>
<p>Tous les espaces de premier niveau sont accessibles dans la liste déroulante située à gauche. Pour modifier, supprimer ou enrichir un espace, il suffit de le sélectionner dans cette liste.<br/>
Le contenu de l'espace sélectionné apparait alors sous cette liste déroulante.
Toutes les opérations disponibles sur cet espace sont accessibles via le menu <b>Que voulez-vous faire ?</b>.<br/>
Vous pouvez notamment :</p>
<ul>
<li>ajouter, modifier, supprimer des applications,</li>
<li>définir les droits d'accès qui s'appliquent à ces applications,</li>
<li>déléguer sa gestion à n'importe quels utilisateurs,</li>
<li>définir une page d'accueil spécifique,</li>
<li>...</li>
</ul>
<p>Pour gérer un sous espace ou une application, le sélectionner vous permettra d'accéder à toutes ses opérations, toujours grâce au menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>.</p>
</div>