<h2 class="txtNav"><center>Willkommen bei der Verwaltung von Bereichen und Anwendungen</center></h2>

<p class="accroche">Silverpeas ist in Bereiche unterteilt, die Anwendungen enthalten. Jeder Bereich kann auch Unterbereiche enthalten.<br/>
$if(communityEnabled)$
Neben den Bereiche ist es möglich, Communities zu erstellen. Dabei handelt es sich um besondere Bereiche, denen die Nutzer selbst beitreten möchten, anstatt dass ihnen ein Administrator den Zugang gewährt.
<br/>
$endif$
Es steht Ihnen eine große Auswahl an gebrauchsfertigen Anwendungen zur Verfügung, die all Ihren Anforderungen gerecht werden: Dokumentenverwaltung, Bildergalerie, Blog, Umfragen, Projektverwaltung...<br/>
Als <b>Bereichsverwalter</b> können Sie alle Bereiche, für die Sie zuständig sind, frei verwalten.</p>

<div id="txt_evolutivite">
<h3>Die Struktur Ihres Bereichs zu ändern ist ein Kinderspiel!</h3>
<p>Alle Bereiche der ersten Ebene sind in der Dropdown-Liste auf der linken Seite zugänglich. Um einen Bereich zu ändern, zu löschen oder zu ergänzen, wählen Sie ihn einfach aus dieser Liste aus.<br/>
Der Inhalt des ausgewählten Bereichs wird dann unter dieser Dropdown-Liste angezeigt.
Alle für diesen Bereich verfügbaren Vorgänge sind über das Menü <b>Was möchten Sie tun?</b> zugänglich.<br/>
Sie können insbesondere:</p>
<ul>
<li>Anwendungen hinzufügen, ändern oder löschen,</li>
<li>die für diese Anwendungen geltenden Zugriffsrechte festlegen,</li>
<li>die Verwaltung an beliebige Benutzer delegieren,</li>
<li>eine bestimmte Startseite festlegen,</li>
<li>...</li>
</ul>
<p>Um einen Unterbereich oder eine Anwendung zu verwalten, wählen Sie diese aus, um über das Menü <b>Was möchten Sie tun?</b> auf alle Funktionen zuzugreifen.</p>
</div>