</div>
<div style="background-color:#353535;color:#FFF;padding:10px;font-family:Century Gothic,Arial;font-size:12px;">
Synthèse de notifications envoyée à partir de <a style="color:#FFF;" href="$notification_serverurl$">votre plateforme Silverpeas</a>
 - <img height="22px" style="vertical-align:middle" src="http://www.silverpeas.com/images/favicon.png" alt="" />
$if(delay)$
<p>Vous en recevrez une nouvelle $delay$.<br/>
Vous pouvez à tout moment changer la fréquence de réception de cette synthèse depuis le paramétrage de <b>"Mes notifications"</b> accessible depuis votre <b>espace personnel</b>.
</p>
$else$
<p>Vous avez choisi de ne plus recevoir de synthèse de notifications.<br/>
Si vous le souhaitez, vous pouvez de nouveau recevoir cette synthèse via le paramétrage de <b>"Mes notifications"</b> accessible depuis votre <b>espace personnel</b>.
</p>
$endif$
</div>