</div>
<div style="background-color:#353535;color:#FFF;padding:10px;font-family:Century Gothic,Arial;font-size:12px;">
Notification synthesis sent from <a style="color:#FFF;" href="$notification_serverurl$">your Silverpeas platform</a>
 - <img height="22px" style="vertical-align:middle" src="http://www.silverpeas.com/images/favicon.png" alt="" />
$if(delay)$
<p>You will receive a new one $delay$.<br/>
You can change whenever you want the receive frequency of this notification synthesis from the settings of <b>"My notifications"</b> from your <b>personnal space</b>.
</p>
$else$
<p>You have chosen to stop receiving notification synthesis.<br/>
If you wish, you can again receive this synthesis from the settings of <b>"My notifications"</b> accessible from your <b>personal space</b>.
</p>
$endif$
</div>