</div>
<div style="background-color:#353535;color:#FFF;padding:10px;font-family:Century Gothic,Arial;font-size:12px;">
Benachrichtigungs Synthese von <a style="color:#FFF;" href="$notification_serverurl$">Ihrer Plattform Silverpeas geschickt</a>
 - <img height="22px" style="vertical-align:middle" src="http://www.silverpeas.com/images/favicon.png" alt="" />
$if(delay)$
<p>Sie werden ein neues $delay$ erhalten.<br/>
Sie können ändern, wann immer Sie die Empfangsfrequenz dieser Mitteilung Synthese aus den Einstellungen <b>"Meine Benachrichtigungen"</b> von Ihrem <b>persönlichen Bereich</b> wollen.
</p>
$else$
<p>Sie haben sich für den Empfang von Meldung Synthese.<br/>
Wenn Sie möchten, können Sie wieder erhalten diese Synthese aus den Einstellungen der <b>"Meine Benachrichtigungen"</b> zugänglich von Ihrem <b>persönlichen Bereich</b>.
</p>
$endif$
</div>