<img src="http://www.silverpeas.com/images/logo.png" alt="" />
<div style="font-family:Century Gothic,Arial;font-size:12px;padding:10px; background-color:#F5F5F5; border:1px solid #ccc">
<div id="header">
	Hello $userName$,<br/><br/>
	Since your last notification synthesis, you have been notified <b>$nbNotifications$ time$if(severalNotifications)$s$endif$</b>$if(severalResources)$ spread over <b>$nbResources$ different contributions</b>$endif$.
</div><br/>