ALTER TABLE SB_Pdc_Axis		DROP CONSTRAINT PK_Pdc_Axis;
ALTER TABLE SB_Pdc_Utilization	DROP CONSTRAINT PK_Pdc_Utilization;
ALTER TABLE SB_Pdc_AxisI18N	DROP CONSTRAINT PK_Pdc_AxisI18N;

alter table PdcPosition_PdcAxisValue drop FK_PdcPosition_PdcAxisValue_AxisValuesId;
alter table PdcPosition_PdcAxisValue drop FK_PdcPosition_PdcAxisValue_PdcPositionId;
alter table PdcClassification_PdcPosition drop constraint FK_PdcClassification_PdcPosition_PositionId;
alter table PdcClassification_PdcPosition drop constraint FK_PdcClassification_PdcPosition_PositionId_PdcClassificationId;