ALTER TABLE ST_Group ADD creationDate TIMESTAMP;
ALTER TABLE ST_Group ADD saveDate TIMESTAMP;
ALTER TABLE ST_Group ADD state VARCHAR(30);
ALTER TABLE ST_Group ADD stateSaveDate TIMESTAMP;

UPDATE ST_Group
SET
    state = 'VALID',
    stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_Group MODIFY state NOT NULL;
ALTER TABLE ST_Group MODIFY stateSaveDate  NOT NULL;