package com.silverpeas.socialnetwork.authentication;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.social.connect.UserProfile;

import com.silverpeas.admin.service.UserService;
import com.silverpeas.admin.service.UserServiceProvider;
import com.silverpeas.socialnetwork.model.ExternalAccount;
import com.silverpeas.socialnetwork.model.SocialNetworkID;
import com.silverpeas.socialnetwork.service.AccessToken;
import com.silverpeas.socialnetwork.service.SocialNetworkAuthorizationException;
import com.silverpeas.socialnetwork.service.SocialNetworkService;
import com.silverpeas.socialnetwork.service.SocialNetworkServiceProvider;
import com.stratelia.silverpeas.silvertrace.SilverTrace;
import com.stratelia.webactiv.beans.admin.AdminException;

/**
 * Controller to log remote social network users into Silverpeas
 *
 * @author Ludovic BERTIN
 *
 */
public class SocialNetworkLoginController extends HttpServlet {

	private static final long serialVersionUID = 3019716885114707069L;

	private UserService userService = null;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		processLogin(req, resp);
	}

	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		processLogin(req, resp);
	}

	@Override
	public void init() throws ServletException {
		super.init();
		userService = UserServiceProvider.getInstance().getService();
	}

	/**
	 * Process Handshake to authenticate user in remote social network
	 * and then log user in Silverpeas.
	 *
	 * If no account has been created yet, it is automatically generated by get user's remote social network profile info.
	 *
	 * @param req		HTTP request
	 * @param resp		HTTP response
	 *
	 * @throws IOException
	 * @throws ServletException
	 */
	private void processLogin(HttpServletRequest req, HttpServletResponse resp) throws IOException, ServletException {
		String command = req.getParameter("command");

		// First step, check Linked authentication
		if (command==null) {
			String networkId = req.getParameter("networkId");
			String authenticateURL = getSocialNetworkAuthenticateURL(networkId);
			resp.sendRedirect(authenticateURL);
		}

		// Then
		else if ("backFromSocialNetworkAuthentication".equals(command)) {
			String networkId = req.getParameter("networkId");
			SocialNetworkService service = getSocialNetworkService(networkId);

			AccessToken authorizationToken;
			try {
				authorizationToken = service.exchangeForAccessToken(req, getRedirectURL(networkId));
			} catch (SocialNetworkAuthorizationException e) {
				resp.sendRedirect("/Login.jsp");
				return;
			}
			req.getSession().setAttribute(SocialNetworkService.AUTHORIZATION_TOKEN_SESSION_ATTR, authorizationToken);
      req.getSession().setAttribute(SocialNetworkService.SOCIALNETWORK_ID_SESSION_ATTR, SocialNetworkID.valueOf(networkId));

			// Try to retrieve a silverpeas account linked to remote social network account
			String profileId = service.getUserProfileId(authorizationToken);
			ExternalAccount account = service.getExternalAccount(SocialNetworkID.valueOf(networkId), profileId);

			// no Silverpeas account yet
			if (account == null) {
				UserProfile profile = service.getUserProfile(authorizationToken);
				req.setAttribute("userProfile", profile);
				req.setAttribute("networkId", networkId);
				req.getRequestDispatcher("/admin/jsp/registerFromRemoteSocialNetwork.jsp").forward(req, resp);
			}

			// Silverpeas account found, log user
			else {
			  RequestDispatcher dispatcher = req.getRequestDispatcher("/AuthenticationServlet");
        dispatcher.forward(req, resp);
			}
		}

		// Silverpeas registration
		else if ("register".equals(command)) {
			String networkId = req.getParameter("networkId");
			SocialNetworkService socialNetworkService = getSocialNetworkService(networkId);

			String firstName = req.getParameter("firstName");
			String lastName = req.getParameter("lastName");
			String email = req.getParameter("email");

			try {
				String userId = userService.registerUser(firstName, lastName, email);
				AccessToken authorizationToken = (AccessToken) req.getSession().getAttribute(SocialNetworkService.AUTHORIZATION_TOKEN_SESSION_ATTR);
				String profileId = socialNetworkService.getUserProfileId(authorizationToken);
				socialNetworkService.createExternalAccount(SocialNetworkID.valueOf(networkId), userId, profileId);
			} catch (AdminException e) {
			  SilverTrace.error("socialNetwork", "SocialNetworkLoginController.register", "socialNetwork.EX_CANT_REGISTER_USER");
			  RequestDispatcher dispatcher = req.getRequestDispatcher("/admin/jsp/alreadyRegistered.jsp");
	      dispatcher.forward(req, resp);
	      return;
			}

			// Forward to authentication servlet
			RequestDispatcher dispatcher = req.getRequestDispatcher("/AuthenticationServlet");
      dispatcher.forward(req, resp);
		}

	}

	private String getRedirectURL(String networkId) {
		StringBuffer redirectURL = new StringBuffer("http://localhost:8000/silverpeas/SocialNetworkLogin?command=backFromSocialNetworkAuthentication&networkId=");
		redirectURL.append(networkId);

		return redirectURL.toString();
	}

	private SocialNetworkService getSocialNetworkService(String networkId) {
		return SocialNetworkServiceProvider.getInstance().getSocialNetworkService(networkId);
	}

	/**
	 * Get URL to invoke remote social network authentication
	 *
	 * @return
	 */
	private String getSocialNetworkAuthenticateURL(String networkId) {
		return getSocialNetworkService(networkId).buildAuthenticateUrl( getRedirectURL(networkId) );
	}

}
