DROP INDEX ST_NotifAddress.IN_NotifAddress_1;

DROP INDEX ST_NotifPreference.IN_NotifPreference_1;

DROP INDEX ST_NotifSended.IN_NotifSended;

DROP INDEX ST_NotifSendedReceiver.IN_NotifSendedReceiver;

DROP INDEX st_delayednotification.idx_st_delayednotification_id;
DROP INDEX st_delayednotification.idx_st_delayednotification_userId;
DROP INDEX st_delayednotification.idx_st_delayednotification_channel;

DROP INDEX st_notificationresource.idx_st_notificationresource_id;
DROP INDEX st_notificationresource.idx_st_notificationresource_resourceId;

DROP INDEX st_delayednotifusersetting.idx_st_delayednotifusersetting_id;
DROP INDEX st_delayednotifusersetting.idx_st_delayednotifusersetting_userId;
DROP INDEX st_delayednotifusersetting.idx_st_delayednotifusersetting_channel;
DROP INDEX st_delayednotifusersetting.idx_st_delayednotifusersetting_uc;