ALTER TABLE SB_Thesaurus_Vocabulary  WITH NOCHECK ADD
CONSTRAINT PK_Thesaurus_Vocabulary PRIMARY KEY  CLUSTERED
(
	id
)
;


ALTER TABLE SB_Thesaurus_Jargon  WITH NOCHECK ADD
CONSTRAINT PK_Thesaurus_Jargon PRIMARY KEY  CLUSTERED
(
	id
)
;


ALTER TABLE SB_Thesaurus_Synonym  WITH NOCHECK ADD
CONSTRAINT PK_Thesaurus_Synonym PRIMARY KEY  CLUSTERED
(
	id
)
;
