CREATE TABLE ST_User_2FA_Recovery
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId    INT         NOT NULL,
    hash      VARCHAR(64) NOT NULL,
    used      BOOLEAN     NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP   NOT NULL,
    usedAt    TIMESTAMP
);

ALTER TABLE ST_User_2FA_Recovery
    ADD CONSTRAINT FK_User_2FA_Recovery_User
        FOREIGN KEY (userId) REFERENCES ST_User(id);

CREATE INDEX IDX_User_2FA_Recovery_User
    ON ST_User_2FA_Recovery (userId);