<p>
La règle <b>$rule$</b> a bien été enregistrée dans le fichier de propriétés <b>$propertyFile$</b>
 et sera appliquée dès les prochaines synchronisations de comptes utilisateur.
</p>
<p>
Veuillez cependant <b>reporter la règle</b> dans le fichier <b>"customer settings"</b> au niveau de la clé <b>$key$</b>
afin que cette dernière ne soit pas écrasée lors d'une prochaine mise à jour de Silverpeas.
</p>