<style type="text/css">
  .ui-tooltip, .qtip{
    max-width: 600px;
  }
  div.domainUserFilterRuleHelp {
    max-width: 600px;
    max-height: 300px;
    overflow-x: hidden;
    overflow-y: auto;
  }
  .domainUserFilterRuleHelp .precision {
     font-size: 0.8em
  }
  .domainUserFilterRuleHelp .precision a {
     font-size: 0.9em
  }
  .domainUserFilterRuleHelp li {
    padding-bottom: 7px;
  }
  .domainUserFilterRuleHelp .code {
    font-weight: bold;
    font-family: "Courier New", "Verdana", "Arial", sans-serif;
  }
</style>
<script type="text/javascript">
  TipManager.simpleHelp(".prefixedNotationHelp", "$prefixedNotationHelp$", {
    show : {
      solo : false
    }
  });
</script>
