<p>
La regla <b>$rule$</b> se ha guardado en el archivo de propiedades <b>$propertyFile$</b>
y se aplicará a partir de las próximas sincronizaciones de cuentas de usuario.
</p>
<p>
Sin embargo, <b>informe la regla</b> en el archivo de <b>&quot;configuración del cliente&quot;</b> al nivel de la clave <b>$key$</b>
para que este último no se sobrescriba durante una futura actualización de Silverpeas.
</p>
