<p><b>Introduzca su búsqueda directamente</b> .<br/><img src="/silverpeas/directory/jsp/images/recherche.png" alt="" /><br/>
¡Atención! Se relaciona con el apellido y el nombre de la persona que está buscando, pero también con otra información: función, departamento, superior, dirección, etc.</p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">o</span> ver alfabéticamente</b> por apellido <img style="float:right"src="/silverpeas/directory/jsp/images/alphabet.png" alt="" /><br/></p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">o</span> filtrar por estado</b><img style="float:right"src="/silverpeas/directory/jsp/images/connectes.png" alt="" /><br/>
</p>
