<p><b>Введіть пошуковий запит безпосередньо</b> .<br/><img src="/silverpeas/directory/jsp/images/recherche.png" alt="" /><br/>
Увага! Це стосується прізвища та імені особи, яку ви шукаєте, а також іншої інформації: посади, відділу, керівника, адреси тощо.</p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">або</span> переглянути в алфавітному порядку</b> за прізвищем <img style="float:right"src="/silverpeas/directory/jsp/images/alphabet.png" alt="" /><br/></p>
<hr style="clear:both;border:0;border-bottom:2px dotted #dddddd;height:0; background-color:transparent;"/>
<p><b><span style="color:#f1790f;">або</span> фільтрувати за статусом</b><img style="float:right"src="/silverpeas/directory/jsp/images/connectes.png" alt="" /><br/>
</p>
