Lista de grupos que están <b>pendientes de eliminación permanente</b> .
<p>
En este nivel, es posible:
<ul>
<li>restaurar grupos. También se restituyen los derechos a los que estaban vinculados <b>en el momento de su supresión</b> .</li>
<li><b>Eliminar grupos de forma permanente</b> .</li>
</ul>
</p>
$if(dayDelay)$
Para cada uno de los grupos, el borrado definitivo lo realiza <b>automáticamente</b> el sistema dentro de <b>$dayDelay$</b> días.
$endif$
