List of <b>removed</b> users.
<p>
At this level, it is possible to:
<ul>
<li>restore users. Their groups and their attached access rights <b>at the time of their removal</b> will be also restored.</li>
<li><b>delete permanently</b> users.</li>
</ul>
</p>
$if(dayDelay)$
For each user, the permanent deletion is performed <b>automatically</b> by the system within a delay of <b>$dayDelay$</b> days.
$endif$