Liste des utilisateurs qui sont <b>en attente de suppression définitive</b>.
<p>
A ce niveau, il est possible de :
<ul>
<li>restaurer des utilisateurs. Leurs groupes et leurs droits auxquels ils étaient liés <b>au moment de leur suppression</b> sont également restaurés.</li>
<li><b>supprimer définitivement</b> des utilisateurs.</li>
</ul>
</p>
$if(dayDelay)$
Pour chacun des utilisateurs, la suppression définitive est réalisée <b>automatiquement</b> par le système dans un délai de <b>$dayDelay$</b> jours.
$endif$