List of <b>removed</b> users.
<p>
At this level, it is possible to :
<ul>
<li>restore users. Their groups and their rights to which they belonged <b>at time of their remove</b> are also restored.</li>
<li><b>delete permanently</b> users.</li>
</ul>
</p>
$if(dayDelay)$
For each user, the permanent deletion is performed <b>automatically</b> by the system within a delay of <b>$dayDelay$</b> days.
$endif$