Liste des groupes qui sont <b>en attente de suppression définitive</b>.
<p>
A ce niveau, il est possible de :
<ul>
<li>restaurer des groupes. Leurs droits auxquels ils étaient liés <b>au moment de leur suppression</b> sont également restaurés.</li>
<li><b>supprimer définitivement</b> des groupes.</li>
</ul>
</p>
$if(dayDelay)$
Pour chacun des groupes, la suppression définitive est réalisée <b>automatiquement</b> par le système dans un délai de <b>$dayDelay$</b> jours.
$endif$