Lista de usuarios que están <b>pendientes de eliminación definitiva</b> .
<p>
En este nivel, es posible:
<ul>
<li>restaurar usuarios. También se restituyen sus grupos y derechos a los que estaban vinculados <b>en el momento de su supresión</b> .</li>
<li><b>eliminar usuarios de forma permanente</b> .</li>
</ul>
</p>
$if(dayDelay)$
Para cada uno de los usuarios, el borrado permanente lo realiza <b>automáticamente</b> el sistema dentro de <b>$dayDelay$</b> días.
$endif$
