ALTER TABLE ST_PortletColumn ADD CONSTRAINT PK_PortletColumn PRIMARY KEY(id);
ALTER TABLE ST_PortletColumn ADD CONSTRAINT FK_PortletColumn_1 FOREIGN KEY(spaceId) REFERENCES ST_Space (id);

ALTER TABLE ST_PortletRow ADD CONSTRAINT PK_PortletRow PRIMARY KEY(id);
ALTER TABLE ST_PortletRow ADD CONSTRAINT FK_PortletRow_1 FOREIGN KEY(instanceId) REFERENCES ST_ComponentInstance(id);
ALTER TABLE ST_PortletRow ADD CONSTRAINT FK_PortletRow_2 FOREIGN KEY(portletColumnId) REFERENCES ST_PortletColumn (id);

ALTER TABLE ST_PortletState ADD CONSTRAINT PK_PortletState PRIMARY KEY(id);
ALTER TABLE ST_PortletState ADD CONSTRAINT FK_PortletState_1 FOREIGN KEY(PortletRowId) REFERENCES ST_PortletRow(id);
ALTER TABLE ST_PortletState ADD CONSTRAINT FK_PortletState_2 FOREIGN KEY(userId) REFERENCES ST_User(id);

ALTER TABLE ST_Component ADD CONSTRAINT PK_Component PRIMARY KEY(id);
ALTER TABLE ST_Component ADD CONSTRAINT UN_ST_Component_1 UNIQUE(componentName);

