<div class="inlineMessage">
<b>Simplify the update of your contents!</b> The <i>Variables</i> tool allows you to manage a list of variables and to associate to each of them a value. <br/>
This value can be changed at any time. The change will then be immediately visible in all content that uses it. <br/>
A very practical solution for phone numbers, addresses, prices, web addresses ... <br/>
From the WYSIWYG editor, contributors can quickly insert these variables through an exclusive plugin. <br/>
<b>Bonus: Anticipate changes!</b> For the same variable, you can define different values for given periods. Changes will be made automatically at the right time.
</div>