<div class="inlineMessage">
<b>¡Simplifique la actualización de su contenido!</b> La herramienta <i>Variables</i> le permite administrar una lista de variables y asociar un valor a cada una.<br/>
Este valor se puede cambiar en cualquier momento. La modificación será inmediatamente visible en todo el contenido que la utilice.<br/>
Una solución muy práctica para números de teléfono, direcciones, tarifas, direcciones web...<br/>
Desde el editor WYSIWYG, los colaboradores pueden insertar rápidamente estas variables gracias a un complemento exclusivo.<br/>
<b>Bonificación: ¡Anticipa los cambios!</b> Para una misma variable, puede definir diferentes valores en períodos determinados. Los cambios se realizarán automáticamente en el momento adecuado.
</div>
