<div class="inlineMessage">
<b>Simplifiez la mise à jour de vos contenus !</b> L'outil <i>Variables</i> permet de gérer une liste de variables et d'associer à chacune d'elles une valeur.<br/>
Cette valeur peut être modifiée à tout moment. La modification sera alors visible immédiatement dans tous les contenus qui l'utilisent.<br/>
Une solution très pratique pour les numéros de téléphones, les adresses, les tarifs, les adresses web...<br/>
Depuis l'éditeur WYSIWYG, les contributeurs peuvent rapidement insérer ces variables grâce à un plugin exclusif.<br/>
<b>Bonus : Anticipez les changements !</b> Pour une même variable, vous pouvez définir des valeurs différentes sur des périodes données. Les changements seront faits automatiquement au bon moment.
</div>