ALTER TABLE ST_Group ADD COLUMN creationDate TIMESTAMP;
ALTER TABLE ST_Group ADD COLUMN saveDate TIMESTAMP;
ALTER TABLE ST_Group ADD COLUMN state VARCHAR(30);
ALTER TABLE ST_Group ADD COLUMN stateSaveDate TIMESTAMP;

UPDATE ST_Group
SET
    state = 'VALID',
    stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_Group ALTER COLUMN state SET NOT NULL;
ALTER TABLE ST_Group ALTER COLUMN stateSaveDate SET NOT NULL;