ALTER TABLE ST_Group ADD COLUMN creationDate TIMESTAMP;
ALTER TABLE ST_Group ADD COLUMN saveDate TIMESTAMP;
ALTER TABLE ST_Group ADD COLUMN state VARCHAR(30);
ALTER TABLE ST_Group ADD COLUMN stateSaveDate TIMESTAMP;