<style type="text/css">
  .ui-tooltip, .qtip{
    max-width: 600px;
  }
  div.synchronizationRuleHelp {
    max-width: 600px;
    max-height: 300px;
    overflow-x: hidden;
    overflow-y: auto;
  }
  .synchronizationRuleHelp li {
    padding-bottom: 7px;
  }
  .synchronizationRuleHelp .example {
    padding-left: 25px;
    padding-right: 25px;
    font-family: "Courier New", "Verdana", "Arial", sans-serif;
  }
  .synchronizationRuleHelp li .example {
    padding-left: 0;
    padding-right: 0;
  }
</style>
<script type="text/javascript">
  TipManager.simpleHelp(".prefixedNotationHelp", "$prefixedNotationHelp$", {
    show : {
      solo : false
    }
  });
</script>
