ALTER TABLE ST_PortletColumn DROP CONSTRAINT FK_PortletColumn_1;
ALTER TABLE ST_PortletRow DROP CONSTRAINT FK_PortletRow_1;
ALTER TABLE ST_PortletRow DROP CONSTRAINT FK_PortletRow_2;
ALTER TABLE ST_PortletState DROP CONSTRAINT FK_PortletState_1;
ALTER TABLE ST_PortletState DROP CONSTRAINT FK_PortletState_2;

ALTER TABLE ST_Component DROP CONSTRAINT UN_ST_Component_1;

ALTER TABLE ST_PortletColumn DROP CONSTRAINT PK_PortletColumn;
ALTER TABLE ST_PortletRow DROP CONSTRAINT PK_PortletRow;
ALTER TABLE ST_PortletState DROP CONSTRAINT PK_PortletState;
ALTER TABLE ST_Component DROP CONSTRAINT PK_Component;
