ALTER TABLE ST_UserSetType DROP CONSTRAINT UN_UserSetType_1;

ALTER TABLE ST_UserSet DROP CONSTRAINT FK_UserSet_2;

ALTER TABLE ST_UserSet_UserSet_Rel DROP CONSTRAINT FK_UserSet_UserSet_Rel_1;
ALTER TABLE ST_UserSet_UserSet_Rel DROP CONSTRAINT FK_UserSet_UserSet_Rel_2;
ALTER TABLE ST_UserSet_UserSet_Rel DROP CONSTRAINT no_cycle;

ALTER TABLE ST_UserSet_User_Rel DROP CONSTRAINT FK_UserSet_User_Rel_1;
ALTER TABLE ST_UserSet_User_Rel DROP CONSTRAINT FK_UserSet_User_Rel_2;

ALTER TABLE ST_UserSetType DROP CONSTRAINT PK_UserSetType;
ALTER TABLE ST_UserSet DROP CONSTRAINT PK_UserSet;
ALTER TABLE ST_UserSet_UserSet_Rel DROP CONSTRAINT PK_UserSet_UserSet_Rel;
ALTER TABLE ST_UserSet_User_Rel DROP CONSTRAINT PK_UserSet_User_Rel;
