<h2 class="txtNav"><center>Willkommen beim Bereich & Application Management</center></h2>

<p class="accroche">Silverpeas wird in Bereiche, die Anwendungen enthalten strukturiert. Jeder Bereich kann auch Unterbereiche enthalten.<br/>
Eine breite Palette von gebrauchsfertigen Anwendunge werden angeboten um alle Ihre Bedürfnisse zu erfüllen: Dokumenten-Management, Bildergalerie, Blog, Umfragen, Projektmanagement ...<br/>
Als <b>Administrator</b> können Sie alle Bereiche und Anwendungen verwalten.</p>

<div id="txt_evolutivite">
<h3>Es ist sehr einfach, die Struktur Ihrer Plattform zu ändern!</h3>
<p>Sie können schnell, unter <a class="txtnav" href="CreateSpace">diesem Link</a>, einen Wurzelbereich erstellen oder, Sie können über das "Was wollen Sie tun ?" Menü <b class="yuimenu"> einen Bereich erstellen </b>. <b>Was wollen Sie als Nächstes tun ?</b>.<br/>
</p><p>Alle First-Level-Bereiche sind über der Dropdown-Liste auf der linken Seite zugänglich. So bearbeiten, löschen oder verwalten Sie einen Bereich, wählen Sie es einfach aus dieser Liste.<br/>
Der Inhalt des ausgewählten Bereichs wird dann in dieser Liste angezeigt.
Alle Operationen auf diesem Bereich sind über das Menü <b>Was wollen Sie tun ?</b> erreichbar.<br/>
Sie können insbesondere:</p>
<ul>
<li>Anwendungen Hinzufügen, Bearbeiten oder Entfernen,</li>
<li>die Zugriffsrechte, die für diese Anwendungen gelten definieren,</li>
<li>Verwaltung jedem Benutzer delegieren,</li>
<li>eine bestimmte Startseite definieren,</li>
<li>...</li>
</ul>
<p>Um einen Unterbereich oder eine Anwendung zu verwalten, klicken Sie auf ihren Namen. Es wird Ihnen den Zugriff auf alle mögliche Operationen, über das Menü <b>Was wollen Sie tun ?</b> erlaubt.</p>
</div>

<div id="txt_restauration">
<h3>Oooops Ich habe den falschen Bereich gelöscht!</h3>
<p>Um zu vermeiden dass ein Benutzer eine falsche Handlung macht, werden Bereiche und Anwendungen, nicht dauerhaft gelöscht.<br/>
Man findet sie immer im <a class="txtnav" href="ViewBin">Papierkorb</a>.<br/>
Der Papierkorb ist nur für Administratoren zugänglich. So sind Sie der einzige, der dauerhaft Bereiche oder Anwendungen löschen kann.<br/>
Beachten Sie, dass Sie bei der Wiederherstellung eines Bereichs oder einer Anwendung neue spezifische Zugangsrechte gewähren müssen.</p>
</div>

<div id="txt_maintenance">
<h3>Maintenance-Modus</h3>
<p>Dieser Modus ermöglicht es Ihnen den Zugriff auf der Plattform zu schließen.<br/>
Nur Administratoren können auf die Plattform zugreifen, es ist also nützlich für große Veränderungen.<br/>
Dieser Modus ist auch in jedem Bereich zur Verfügung. Die Nutzer werden von der vorübergehende Nichtverfügbarkeit gewarnt werden.</p>
</div>
