<h2 class="txtNav"><center>Bienvenue sur la gestion des espaces et des applications</center></h2>

<p class="accroche">Silverpeas est structuré en espaces qui contiennent des applications. Chaque espace peut également contenir des sous espaces.<br/>
Un large choix d'applications prêtes à l'emploi vous est offert pour répondre à tous vos besoins : gestion documentaire, galerie d'images, blog, sondages, gestion de projet...<br/>
En tant qu'<b>administrateur de la plateforme</b>, vous pouvez gérer à tout moment l'ensemble des espaces et des applications.</p>

<div id="txt_evolutivite">
<h3>Faire évoluer la structure de votre plateforme est un jeu d'enfant !</h3>
<p>Vous pouvez rapidement créer un espace de premier niveau en <a class="txtnav" href="CreateSpace">cliquant ici</a> ou en choisissant l'opération <b class="yuimenu"> Créer un espace </b> du menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>.</p>
<p>Tous les espaces de premier niveau sont accessibles dans la liste déroulante située à gauche. Pour modifier, supprimer ou enrichir un espace, il suffit de le sélectionner dans cette liste.<br />
Le contenu de l'espace sélectionné apparait alors sous cette liste déroulante. Toutes les opérations disponibles sur l'espace sélectionné sont accessibles via le menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>.<br/>
Vous pouvez notamment :</p>
<ul>
<li>ajouter, modifier, supprimer des applications,</li>
<li>définir les droits d'accès qui s'appliquent à ces applications,</li>
<li>déléguer sa gestion à n'importe quels utilisateurs,</li>
<li>définir une page d'accueil spécifique,</li>
<li>...</li>
</ul>
<p>Pour modifier un sous espace ou une application, le sélectionner vous permettra d'accéder à toutes ses opérations, toujours grâce au menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>.</p>
</div>

<div id="txt_restauration">
<h3>Ouf... la corbeille d'espaces et d'applications est là !</h3>
<p>Afin d'éviter les dégats engendrés par une mauvaise manipulation, les espaces et les applications ne sont pas définitivement supprimés.<br/>
Avant leurs suppressions définitives, ils peuvent être restaurés via la corbeille  en <a class="txtnav" href="ViewBin">cliquant ici</a> ou en choisissant l'opération <b class="yuimenu"> Corbeille d'espaces et d'applications </b> du menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>.<br/>
Cette corbeille est réservée aux administrateurs. Vous êtes donc seul(s) à pouvoir restaurer et supprimer définitivement des espaces ou des applications.<br/>
Il est à noter que lors de la restauration les droits spécifiques doivent être définis de nouveau.</p>
</div>

<div id="txt_maintenance">
<h3>Le mode Maintenance</h3>
<p>Ce mode permet de rendre temporairement indisponible la plateforme.
Utile lors de changements profonds, seuls les administrateurs pourront accéder à la plateforme et à son contenu.<br/>
Ce mode est disponible également au niveau de chaque espace via l'opération <b class="yuimenu"> Activer le mode maintenance </b> du menu <b>Que&nbsp;voulez-vous&nbsp;faire&nbsp;?</b>. <br />Dans ce cas, un message avertit les utilisateurs de l'indisponibilité momentanée.</p>
</div>