<div class="componentNav">

<span class="txtNav"><center>Welcome to the "Space & Applications" manager</center></span><br/>

As an administrator you can manage all the spaces and applications. A space contains applications and also subspaces.

<h2>It's very easy to change the structure of your platform</h2>
You can create a space root quiclky following <a href="javascript:onclick=openPopup('CreateSpace',750,300)">this link</a> or when following right corner operation "Create a space" from menu <b>What do you want to do next ?</b>.
All the space root can be accessed by drop down list in the left panel.  You must select one of those in order to modify, delete or upgrade a space.
You will find available features on current selected space inside <b>What do you want to do next ?</b> menu.

Specifically, you can do :
<ul>
<li>Delegate space management to any user,</li>
<li>Grant access right to applications,</li>
<li>Define a specific home page,</li>
<li>...</li>
</ul>
You will find on the left side the content of the selected space.
You can select any subspace or applications from this left panel in order to interact with using the <b>What do you want to do next ?</b> menu.

<h2>Oups I have deleted the wrong space !!!</h2>
To prevent user from doing some wrong handling, all the spaces and applications are not permanently erased.
You can always find them inside the <a href="ViewBin">bin</a>. 
The bin is only accessible from administrators. So you are the only one who can restore or permanently delete spaces or applications.
Keep in mind that you will need to grant new specific access right when restoring a space or an application.

<h2>Maintenace mode</h2>
This mode allows you to close access to the platform.
Only administrators can access the platform, so it's useful for major changes.
You can activate this mode only at space level. Users will be warned of the temporary unavailability.

</div>