<span class="txtNav"><center>Bienvenue sur la gestion des espaces et des applications</center></span><br/>

Silverpeas est structuré en espaces qui contiennent des applications. Chaque espace peut également contenir des sous espaces.<br/>
Un large choix d'applications prêtes à l'emploi vous est offert pour répondre à tous vos besoins : gestion documentaire, galerie d'images, blog, sondages, gestion de projet...<br/>
En tant qu'<b>administrateur de la plateforme</b>, vous pouvez gérer à tout moment l'ensemble des espaces et des applications.

<h3>Faire évoluer la structure de votre plateforme est un jeu d'enfant !</h3>
Vous pouvez rapidement créer un espace de premier niveau en cliquant <a href="javascript:onclick=openPopup()">ici</a> ou en choisissant l'opération "Créer un espace" du menu <b>Que voulez-vous faire ?</b>.<br/>
Tous les espaces de premier niveau sont accessibles dans la liste déroulante située à gauche. Pour modifier, supprimer ou enrichir un espace, il suffit de le sélectionner dans cette liste.<br/>
Le contenu de l'espace sélectionné apparait alors sous cette liste déroulante.
Toutes les opérations disponibles sur l'espace sélectionné sont accessibles via le menu <b>Que voulez-vous faire ?</b>.<br/>
Vous pouvez notamment :
<ul>
<li>ajouter, modifier, supprimer des applications,</li>
<li>définir les droits d'accès qui s'appliquent à ces applications,</li>
<li>déléguer sa gestion à n'importe quels utilisateurs,</li>
<li>définir une page d'accueil spécifique,</li>
<li>...</li>
</ul>
Pour modifier un sous espace ou une application, un clic sur son nom vous permettra d'accéder à toutes ses opérations, toujours grâce au menu <b>Que voulez-vous faire ?</b>.

<h3>Ouf... la corbeille d'espaces et d'applications est là !</h3>
Afin d'éviter les dégats engendrés par une mauvaise manipulation, les espaces et les applications ne sont pas définitivement supprimés.<br/>
Avant leurs suppressions définitives, ils peuvent être restaurés depuis la <a href="ViewBin">corbeille</a>.<br/>
Cette corbeille est réservée aux administrateurs. Vous êtes donc seul(s) à pouvoir restaurer et supprimer définitivement des espaces ou des applications.<br/>
Il est à noter que lors de la restauration les droits spécifiques doivent être définis de nouveau.

<h3>Le mode Maintenance</h3>
Ce mode permet de rendre temporairement indisponible la plateforme.
Utile lors de changements profonds, seuls les administrateurs pourront accéder à la plateforme et à son contenu.<br/>
Ce mode est disponible également au niveau de chaque espace. Dans ce cas, un message avertit les utilisateurs de l'indisponibilité momentanée.