<div class="componentNav">

<span class="txtNav"><center>Bienvenue sur la gestion des espaces et des applications</center></span><br/>

En tant qu'administrateur de la plateforme, vous pouvez gérer à tout moment l'ensemble des espaces et des applications.
Un espace contient des applications. Il peut également contenir des sous espaces.

<h2>Faire évoluer la structure de votre plateforme est un jeu d'enfant</h2>
Vous pouvez rapidement créer un espace de premier niveau en cliquant <a href="javascript:onclick=openPopup('CreateSpace',750,300)">ici</a> ou en choisissant l'opération "Créer un espace" du menu <b>Que voulez-vous faire ?</b>.
Tous les espaces de premier niveau sont accessibles dans la liste déroulante située à gauche. Pour modifier, supprimer ou enrichir un espace, il suffit de le sélectionner dans cette liste.
Toutes les opérations disponibles sur l'espace sélectionné sont accessibles via le menu <b>Que voulez-vous faire ?</b>.
Vous pouvez notamment :
<ul>
<li>déléguer sa gestion à n'importe quels utilisateurs,</li>
<li>définir les droits d'accès qui s'appliquent aux applications,</li>
<li>définir une page d'accueil spécifique,</li>
<li>...</li>
</ul>
Le contenu de l'espace sélectionné est présenté sur votre gauche. 
Pour modifier un sous espace ou une application, un clic sur son nom vous permettra d'accéder à toutes ses opérations, toujours via le menu <b>Que voulez-vous faire ?</b>.

<h2>Ouf... la corbeille d'espaces et d'applications est là !</h2>
Afin d'éviter les dégats engendrés par une mauvaise manipulation, les espaces et les applications ne sont pas définitivement supprimés.
Avant leurs suppressions définitives, ils peuvent être restaurés depuis la <a href="ViewBin">corbeille</a>.
Cette corbeille est réservée aux administrateurs. Vous êtes donc seul(s) à pouvoir restaurer et supprimer définitivement des espaces ou des applications.
Il est à noter que lors de la restauration les droits spécifiques doivent être défini de nouveau.

<h2>Le mode Maintenance</h2>
Ce mode permet de rendre temporairement indisponible la plateforme.
Utile lors de changements profonds, seuls les administrateurs pourront accéder à la plateforme et à son contenu.
Ce mode est disponible également au niveau de chaque espace. Dans ce cas, un message avertit les utilisateurs de l'indisponibilité momentanée.

</div>