<h2 class="txtNav"><center>Willkommen beim Bereich & Application Management</center></h2>

<p class="accroche">Silverpeas wird in Bereiche, die Anwendungen enthalten strukturiert. Jeder Bereich kann auch Unterbereiche enthalten.<br/>
Eine breite Palette von gebrauchsfertigen Anwendunge werden angeboten um alle Ihre Bedürfnisse zu erfüllen: Dokumenten-Management, Bildergalerie, Blog, Umfragen, Projektmanagement ...<br/>
Als <b>Bereich Verwalter</b>, können Sie alle Bereiche die Ihnen wichtig sind verwalten.</p>

<div id="txt_evolutivite">
<h3>Es ist sehr einfach, die Struktur Ihres Bereichs zu ändern!</h3>
<p>Alle First-Level-Bereiche sind über die Dropdown-Liste auf der linken Seite zugänglich. <br/>Um eine Bereich zu bearbeiten, löschen oder verwalten, wählen Sie ihn einfach aus dieser Liste aus.<br/>
Der Inhalt des ausgewählten Bereichs wird dann in dieser Liste angezeigt.
Alle Operationen auf diesem Bereich sind über das Menü <b>Was wollen Sie tun ?</b> erreichbar..<br/>
Sie können insbesondere:</p>
<ul>
<li>Anwendungen Hinzufügen, Bearbeiten oder Entfernen,</li>
<li>die Zugriffsrechte, die für diese Anwendungen gelten definieren,</li>
<li>Verwaltung jedem Benutzer delegieren,</li>
<li>eine bestimmte Startseite definieren,</li>
<li>...</li>
</ul>
<p>Um einen Unterbereich oder eine Anwendung zu verwalten, klicken Sie auf ihren Namen. Es wird Ihnen den Zugriff auf alle mögliche Operationen, über das Menü <b>Was wollen Sie tun ?</b> erlaubt.</p>
</div>