<h2 class="txtNav"><center>Welcome to space & applications management</center></h2>

<p class="accroche">Silverpeas is structured into spaces that contain applications. Each space may also contains sub-spaces.<br/>
A wide range of applications ready to use is offered to meet all your needs : document management, image gallery, blog, surveys, project management...<br/>
As an <b>administrator</b> you can manage all spaces and applications.</p>

<div id="txt_evolutivite">
<h3>It's very easy to change the structure of your platform !</h3>
<p>You can create a root space quickly following <a class="txtnav" href="CreateSpace">this link</a> or when following right corner operation <b class="yuimenu"> Create a space </b> from menu <b>What do you want to do next ?</b>.<br/>
</p><p>All first-level spaces are accessible in the drop-down list on the left. To edit, delete or manage a space, simply select it from this list.<br/>
The content of the selected space will then appear in this list.
All the operations available on this space are accessible via the menu <b>What do you want to do next?</b>.<br/>
You can especially :</p>
<ul>
<li>add, edit or remove applications,</li>
<li>define the access rights that apply to those applications,</li>
<li>delegate its management to any user,</li>
<li>define a specific home page,</li>
<li>...</li>
</ul>
<p>To manage a subspace or application, click on their name. It will give you access to all its operations, using the menu <b>What do you want to do next?</b>.</p>
</div>

<div id="txt_restauration">
<h3>Oups I have deleted the wrong space !!!</h3>
<p>To prevent user from doing some wrong handling, all the spaces and applications are not permanently erased.<br/>
You can always find them inside the <a class="txtnav" href="ViewBin">bin</a>.<br/>
The bin is only accessible to administrators. So you are the only one(s) who can restore or permanently delete spaces or applications.<br/>
Keep in mind that you will need to grant new specific access right when restoring a space or an application.</p>
</div>

<div id="txt_maintenance">
<h3>Maintenace mode</h3>
<p>This mode allows you to close access to the platform.<br/>
Only administrators can access the platform, so it's useful for major changes.<br/>
This mode is also available in each space. Users will be warned of the temporary unavailability.</p>
</div>