<div class="componentNav">

<span class="txtNav"><center>Welcome to the "Users & groups" module</center></span><br/>
The repository manages which users can access to Silverpeas.<br/>
Each user belongs to a domain. In this area, users can be grouped into groups and subgroups.<br/>
Groups can be managed manually or automatically (synchronized group).<br/>
<br/>
There are several types of domains :
<ul>
<li>users domains<br/>
- $listDomains; separator="<br/> - "$
<br/>
Note that the domain <em>Silverpeas</em> is the default.
<br/>
Other domains can be created manually or be connected to an external directory (LDAP).<br/><br/>
</li>

<li>mixed domain<br/>
No user creation is possible in this domain. <br/>
It simply allows group users from different domains.
</li>
</ul>

</div>
