<div class="componentNav">

<center><span class="txtNav">Bienvenido al módulo &quot;Usuarios y grupos&quot;</span></center><br/>
El repositorio se utiliza para administrar los usuarios autorizados para acceder a Silverpeas.<br/>
Cada usuario pertenece a un dominio. En este dominio, los usuarios se pueden agrupar en grupos y subgrupos.<br/>
Los grupos se pueden gestionar de forma manual o automática (grupo sincronizado).<br/>
<br/>
Hay varios tipos de dominios:
<ul>
<li>dominios de usuario<br/>
- $listDomains; separator="<br/> - "$
<br/>
Tenga en cuenta que el dominio de <em>Silverpeas</em> existe de forma predeterminada.
<br/>
Los otros dominios se pueden crear manualmente o conectarse a un directorio externo (LDAP).<br/><br/>
</li>

<li>el dominio mixto<br/>
No es posible la creación de usuarios en este dominio.<br/>
Simplemente le permite agrupar usuarios de diferentes dominios.
</li>
</ul>

</div>
