<div class="componentNav">

<span class="txtNav"><center>Bienvenue sur le module "Utilisateurs & groupes"</center></span><br/>
Le référentiel permet de gérer les utilisateurs autorisés à accéder à Silverpeas.<br/>
Chaque utilisateur appartient à un domaine. Dans ce domaine, les utilisateurs peuvent être regroupés en groupes et sous groupes.<br/>
Les groupes peuvent être gérés manuellement ou automatiquement (groupe synchronisé).<br/>
<br/>
Il existe plusieurs types de domaines :
<ul>
<li>les domaines utilisateurs<br/>
- $listDomains; separator="<br/> - "$
<br/>
On notera que le domaine <em>Silverpeas</em> existe par défaut.
<br/>
Les autres domaines peuvent être créés manuellement ou être branchés sur un annuaire externe (LDAP).<br/><br/>
</li>

<li>le domaine mixte<br/>
Aucune création d'utilisateur n'est possible sur ce domaine.<br/>
Il permet simplement de regrouper des utilisateurs provenant des différents domaines.
</li>
</ul>

</div>