<img src="http://www.silverpeas.com/images/logo.png" alt="" />
<div style="font-family:Century Gothic,Arial;font-size:12px;padding:10px; background-color:#F5F5F5; border:1px solid #ccc">
<div>
Привет $userName$,<br/><br/>
С момента последней сводки уведомлений вы стали объектом <b>$nbNotifications$ уведомление$if(severalNotifications)$с$endif$</b> $if(severalResources)$ распределенный$if(severalNotifications)$s$endif$ на <b>$nbResources$</b> различные <b>взносы</b> $endif$.
</div><br/>
