<img src="http://www.silverpeas.com/images/logo.png" alt="" />
<div style="font-family:Century Gothic,Arial;font-size:12px;padding:10px; background-color:#F5F5F5; border:1px solid #ccc">
<div>
Привіт $userName$,<br/><br/>
Після вашого останнього підсумку сповіщень ви стали предметом <b>$nbNotifications$ повідомлення$if(severalNotifications)$s$endif$</b> $if(severalResources)$ розподілений$if(severalNotifications)$s$endif$ на <b>$nbResources$</b> різні <b>внески</b> $endif$.
</div><br/>
