<img src="http://www.silverpeas.com/images/logo.png" alt="" />
<div style="font-family:Century Gothic,Arial;font-size:12px;padding:10px; background-color:#F5F5F5; border:1px solid #ccc">
<div>
Hola $userName$,<br/><br/>
Desde su último resumen de notificaciones, ha sido objeto de <b>$nbNotifications$ notificación$if(severalNotifications)$s$endif$</b> $if(severalResources)$ distribuido$if(severalNotifications)$s$endif$ en <b>$nbResources$</b> distintas <b>aportaciones</b> $endif$.
</div><br/>
