<div style="font-family:Arial;font-size:11px">
Bonjour $fullName$,<br/>
<br/>
merci de vous &ecirc;tre registr&eacute; sur notre plateforme.<br/>
En plus de pouvoir vous connecter depuis votre r&eacute;seau social pr&eacute;f&eacute;r&eacute;, vous avez &eacute;galement la possibilit&eacute;
de vous identifier avec les codes suivants : <br/>
<br/>
<b> Login : </b>$login$
<b> Mot de passe : </b>$password$
</div>

Cliquez <a href="$url$">ici</a> pour acc&eacute;der à notre Plateforme.