<div style="font-family:Arial;font-size:11px">
Bonjour $fullName$,<br/>
<br/>
Merci de vous &ecirc;tre enregistr&eacute; sur Silverpeas.<br/>
En plus de pouvoir vous connecter depuis votre r&eacute;seau social pr&eacute;f&eacute;r&eacute;, vous avez &eacute;galement la possibilit&eacute;
de vous identifier avec les codes suivants : <br/>
<br/>
<b>Identifiant : </b>$login$
<b>Mot de passe : </b>$password$
</div>

Pour vous connecter, cliquez <a href="$url$">ici</a>