<%

// Style CSS
String styleSheetSrc                          = m_context + "/util/styleSheets/globalSP.css";

// JavaScript
String javaScriptSrc                          = m_context + "/util/javaScript/animation.js";

// Icones operationBar
String folderAddSrc                           = m_context + "/util/icons/folderAddBig.gif";
String publicationAddSrc					  = m_context + "/util/icons/publicationAdd.gif";
String toolAddSrc                             = m_context + "/util/icons/publicationAdd.gif";
String subscriptionSrc                        = m_context + "/util/icons/subscribe.gif";
String subscriptionAddSrc                     = m_context + "/util/icons/subscribeAdd.gif";
String favoriteSrc                            = m_context + "/util/icons/favorite.gif";
String favoriteAddSrc                         = m_context + "/util/icons/favoriteAdd.gif";
String topicBasketSrc						  = m_context + "/util/icons/basket.gif";
String topicDZSrc							  = m_context + "/util/icons/declassified.gif";
String documentDelSrc						  = m_context + "/util/icons/documentDel.gif";
String versionAddSrc						  = m_context + "/util/icons/docversionAdd.gif";

// Icones diverses
String AttachedFilesSrc					      = m_context + "/util/icons/small/eventAttachedFiles.gif";
String eventSupprSrc						  = m_context + "/util/icons/eventSuppr.gif";
String eventReadSrc							  = m_context + "/util/icons/small/eventRead.gif";
String addEventSrc							  = m_context + "/util/icons/addEvent.gif";
String printSrc                               = m_context + "/util/icons/print.gif";
String pdfSrc                                 = m_context + "/util/icons/pdf.gif";
String toolSrc                                = m_context + "/util/icons/publication.gif";
String folderUpdateSrc                        = m_context + "/util/icons/update.gif";
String folderDeleteSrc                        = m_context + "/util/icons/delete.gif";
String folderSrc                              = m_context + "/util/icons/folder.gif";
String starOn                                 = m_context + "/util/icons/starFilled.gif";
String starOff                                = m_context + "/util/icons/starEmpty.gif";
String buletPoint                             = m_context + "/util/icons/buletGrey.gif";

// Pixels
String orangePix                              = m_context + "/util/icons/colorPix/orange.gif";
String noColorPix                             = m_context + "/util/icons/colorPix/1px.gif";
String ArrayPnoColorPix   					  = m_context + "/util/icons/colorPix/15px.gif";

// Divers
String arrowNavRightOnSrc					  = m_context + "/util/icons/arrow/001arrOrangeRight.gif";
String arrowNavRightOffSrc					  = m_context + "/util/icons/arrow/001arrWhiteRight.gif";
String arrowNavLeftOnSrc					  = m_context + "/util/icons/arrow/001arrOrangeLeft.gif";
String arrowNavLeftOffSrc				      = m_context + "/util/icons/arrow/001arrWhiteLeft.gif";
String arrRight				                  = m_context + "/util/icons/arrow/arrowRight.gif";
String arrLeft				                  = m_context + "/util/icons/arrow/arrowLeft.gif";
String advanceOn                              = m_context + "/util/icons/on.gif";
String advanceOff                             = m_context + "/util/icons/off.gif";
String hLineSrc		                          = m_context + "/util/icons/colorPix/1px.gif";
String modif_icon 							  = m_context + "/util/icons/update.gif";
String delete_icon                            = m_context + "/util/icons/delete.gif";
String mandatory_field                        = m_context + "/util/icons/mandatoryField.gif";
%>