//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.14 at 03:42:33 PM CET 
//
package com.silverpeas.admin.spaces;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameter" type="{http://silverpeas.org/xml/ns/space}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentType", propOrder = {"type", "label", "description", "parameters"})
public class SpaceComponent {

  @XmlElement(required = true)
  protected String type;
  @XmlElement(required = true)
  protected String label;
  @XmlElement(required = true)
  protected String description;
  @XmlElementWrapper(name = "parameters")
  @XmlElement(name = "parameter")
  protected List<SpaceComponentParameter> parameters;

  /**
   * Gets the value of the type property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the label property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getLabel() {
    return label;
  }

  /**
   * Sets the value of the label property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setLabel(String value) {
    this.label = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the parameters property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the parameters property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getParameters().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link SpaceComponentParameter }
   * 
   * 
   */
  public List<SpaceComponentParameter> getParameters() {
    if (parameters == null) {
      parameters = new ArrayList<SpaceComponentParameter>();
    }
    return this.parameters;
  }

  public void setParameters(List<SpaceComponentParameter> value) {
    this.parameters = value;
  }
}
