//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.14 at 03:42:33 PM CET 
//
package com.silverpeas.admin.spaces;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for SpaceTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpaceTemplateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="components">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="component" type="{http://silverpeas.org/xml/ns/space}ComponentType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpaceTemplateType", propOrder = {"template", "defaultName", "description",
  "readonly", "components"})
public class SpaceTemplate {

  @XmlElement(required = true)
  protected String template;
  @XmlElement(required = true)
  protected String defaultName;
  @XmlElement(required = true)
  protected String description;
  protected boolean readonly;
  @XmlElementWrapper(name = "components")
  @XmlElement(name = "component")
  protected List<SpaceComponent> components;

  /**
   * Gets the value of the template property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getTemplate() {
    return template;
  }

  /**
   * Sets the value of the template property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setTemplate(String value) {
    this.template = value;
  }

  /**
   * Gets the value of the defaultName property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getDefaultName() {
    return defaultName;
  }

  /**
   * Sets the value of the defaultName property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setDefaultName(String value) {
    this.defaultName = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return
   *     possible object is
   *     {@link String }
   *     
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *     allowed object is
   *     {@link String }
   *     
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the readonly property.
   * 
   */
  public boolean isReadonly() {
    return readonly;
  }

  /**
   * Sets the value of the readonly property.
   * 
   */
  public void setReadonly(boolean value) {
    this.readonly = value;
  }

  /**
   * Gets the value of the components property.
   * 
   * @return
   *     possible object is
   *     {@link SpaceComponent }
   *     
   */
  public List<SpaceComponent> getComponents() {
    return components;
  }

  /**
   * Sets the value of the components property.
   * 
   * @param value
   *     allowed object is
   *     {@link SpaceComponent }
   *     
   */
  public void setComponents(List<SpaceComponent> value) {
    this.components = value;
  }
}
