DROP INDEX IN_NotifAddress_1;

DROP INDEX IN_NotifPreference_1;

DROP INDEX IN_NotifSended;

DROP INDEX IN_NotifSendedReceiver;

DROP INDEX idx_st_delayednotification_id;
DROP INDEX idx_st_delayednotification_userId;
DROP INDEX idx_st_delayednotification_channel;

DROP INDEX idx_st_notificationresource_id;
DROP INDEX idx_st_notificationresource_resourceId;

DROP INDEX idx_st_delayednotificationusersetting_id;
DROP INDEX idx_st_delayednotificationusersetting_userId;
DROP INDEX idx_st_delayednotificationusersetting_channel;
DROP INDEX idx_st_delayednotificationusersetting_uc;