DROP INDEX R_24_FK;

DROP INDEX SR_UNINSTITEMS_I1;

DROP INDEX RELATION_46_FK;

DROP INDEX SR_ITEM_ID;

DROP INDEX IN_DEPENDENCIES_1;

ALTER TABLE SR_UNINSTITEMS DROP CONSTRAINT PK_SR_UNINSTITEMS;

DROP TABLE SR_RELLOG2;

DROP TABLE SR_UNINSTITEMS;

DROP TABLE SR_SCRIPTS;

DROP TABLE SR_DEPENDENCIES;