DragAndDropUploadBundle = новый SilverpeasPluginBundle({
&quot;droparea.miss&quot;: &quot;Пожалуйста, перетащите ваши файлы над областью, предназначенной для этой цели&quot;,
&quot;droparea.folder.error&quot;: &quot;Ваш веб-браузер не поддерживает перетаскивание папок&quot;,
&quot;upload.inprogress&quot;:&quot;Файлы загружаются,<br/> пожалуйста, не продолжайте просмотр, пока это не будет завершено&quot;
});
