DragAndDropUploadBundle = nuevo SilverpeasPluginBundle({
&quot;dropeaa.miss&quot;: &quot;Por favor, suelte sus archivos sobre el área provista para este propósito&quot;,
&quot;droparea.folder.error&quot;: &quot;Su navegador WEB no admite la eliminación de carpetas&quot;,
&quot;upload.inprogress&quot;:&quot;Los archivos se están cargando,<br/> por favor, no continúe navegando hasta que esto esté completo&quot;
});
