
    create table PdcAxisValue (
        id bigint generated by default as identity,
        axisId bigint,
        term varchar(255),
        parent_id bigint,
        primary key (id)
    );

    create table PdcClassification (
        id bigint generated by default as identity,
        contentId varchar(255),
        instanceId varchar(255) not null,
        modifiable bit not null,
        nodeId varchar(255),
        primary key (id)
    );

    create table PdcClassification_PdcPosition (
        PdcClassification_id bigint not null,
        positions_id bigint not null,
        primary key (PdcClassification_id, positions_id),
        unique (positions_id)
    );

    create table PdcPosition (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table PdcPosition_PdcAxisValue (
        PdcPosition_id bigint not null,
        axisValues_id bigint not null,
        primary key (PdcPosition_id, axisValues_id),
        unique (axisValues_id)
    );

    alter table PdcAxisValue 
        add constraint FKDBC2B6414B9295A2 
        foreign key (parent_id) 
        references PdcAxisValue;

    alter table PdcClassification_PdcPosition 
        add constraint FKDB93406E747FC777 
        foreign key (positions_id) 
        references PdcPosition;

    alter table PdcClassification_PdcPosition 
        add constraint FKDB93406E8EE2BDA9 
        foreign key (PdcClassification_id) 
        references PdcClassification;

    alter table PdcPosition_PdcAxisValue 
        add constraint FK978A70086C4C2BA9 
        foreign key (axisValues_id) 
        references PdcAxisValue;

    alter table PdcPosition_PdcAxisValue 
        add constraint FK978A70086022C209 
        foreign key (PdcPosition_id) 
        references PdcPosition;
