ALTER TABLE ST_User ADD creationDate DATETIME;
ALTER TABLE ST_User ADD saveDate DATETIME;
ALTER TABLE ST_User ADD version INT DEFAULT 0 NOT NULL;
ALTER TABLE ST_User ADD tosAcceptanceDate DATETIME;
ALTER TABLE ST_User ADD lastLoginDate DATETIME;
ALTER TABLE ST_User ADD nbSuccessfulLoginAttempts INT DEFAULT 0 NOT NULL;
ALTER TABLE ST_User ADD lastLoginCredentialUpdateDate DATETIME;
ALTER TABLE ST_User ADD expirationDate DATETIME;
ALTER TABLE ST_User ADD state VARCHAR(30);
ALTER TABLE ST_User ADD stateSaveDate DATETIME;

UPDATE ST_User
SET
  state = (CASE WHEN accessLevel = 'R' THEN 'DELETED'
           ELSE 'VALID' END),
  stateSaveDate = CURRENT_TIMESTAMP;

ALTER TABLE ST_User ALTER COLUMN state VARCHAR(30) NOT NULL;
ALTER TABLE ST_User ALTER COLUMN stateSaveDate DATETIME NOT NULL;