package com.stratelia.webactiv.util.viewGenerator.html.dateReminder;

import java.util.Date;
import com.stratelia.webactiv.util.DateUtil;
import com.stratelia.webactiv.util.ResourceLocator;
import com.stratelia.webactiv.util.publication.model.PublicationDetail;
import org.silverpeas.EntityReference;
import org.silverpeas.dateReminder.persistent.service.DateReminderServiceFactory;
import org.silverpeas.dateReminder.persistent.service.PersistentDateReminderService;
import org.silverpeas.dateReminder.persistent.PersistentResourceDateReminder;
import org.silverpeas.dateReminder.persistent.DateReminderDetail;
import org.silverpeas.publication.dateReminder.PublicationNoteReference;

/**
 * The widget date reminder
 *
 * @author Cécile Bonin
 */
public class DateReminder {

  private String resourceId;
  private String resourceType;
  private String userId;
  private String language;
  private ResourceLocator messages;

  public DateReminder(String resourceId,
      String resourceType, String userId, String language) {
    this.resourceId = resourceId;
    this.resourceType = resourceType;
    this.userId = userId;
    this.language = language;
    this.messages = new ResourceLocator("org.silverpeas.dateReminder.multilang.dateReminder", language);
  }

  /**
   * Sets the unique identifier of the resource that use DateReminder.
   *
   * @param resourceId the unique identifier of the resource.
   */
  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  /**
   * Sets the type of the resource that use DateReminder.
   *
   * @param resourceType the type of the resource.
   */
  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  /**
   * Sets the unique identifier of the user that requested the page in which will be rendered the
   * widget.
   *
   * @param userId the user identifier.
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * Sets the language that requested the page in which will be rendered the
   * widget.
   *
   * @param language the user identifier.
   */
  public void setLanguage(String language) {
    this.language = language;
  }

  /**
   * Gets the unique identifier of the resource in Silverpeas.
   *
   * @return the resource identifier.
   */
  public String getResourceId() {
    return resourceId;
  }

  /**
   * Gets the type of the resource.
   *
   * @return
   */
  public String getResourceType() {
    return resourceType;
  }

  /**
   * Gets the unique identifier of the user that requested the page in which will be rendered the
   * widget.
   *
   * @return the unique identifier of the user.
   */
  public String getUserId() {
    return userId;
  }

  /**
   * Gets the language that requested the page in which will be rendered the
   * widget.
   *
   * @return the language.
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Gets the html code generated by the widget.
   *
   * @return the code.
   */
  public String print() {

    StringBuilder builder = new StringBuilder(100);

    String dateReminder = "";
    String messageReminder = "";
    EntityReference resource = null;

    if(PublicationDetail.getResourceType().equals(getResourceType())) {//The resource is a publication
      if(this.getResourceId() != null) {//Case of updating an existing publication
        resource = new PublicationNoteReference(this.getResourceId());
      }
    }

    if (resource != null) {//Case of updating an existing publication
      PersistentDateReminderService dateReminderService = DateReminderServiceFactory.getDateReminderService();
      PersistentResourceDateReminder persistentResourceDateReminder = dateReminderService.get(resource);
      if (persistentResourceDateReminder.isDefined()) {
        DateReminderDetail dateReminderDetail = persistentResourceDateReminder.getDateReminder();
        Date dateReminderDate = dateReminderDetail.getDateReminder();

        //initialize the date reminder and message to be displayed
        dateReminder = DateUtil.dateToString(dateReminderDate, getLanguage());
        messageReminder = dateReminderDetail.getMessage();
      }
    }

    builder.append("<fieldset id=\"reminder\" class=\"skinFieldset\">").append("\n");
    builder.append("<legend>").append(this.messages.getString("dateReminder.fieldSet")).append("</legend>").append("\n");

    builder.append("<div class=\"fields\">").append("\n");

    builder.append("<div class=\"field\" id=\"dateReminderArea\">").append("\n");
    builder.append("<label for=\"dateReminder\" class=\"txtlibform\">").append(
        this.messages.getString("dateReminder.date")).append("</label>").append("\n");
    builder.append("<div class=\"champs\">").append("\n");
    builder.append("<input id=\"dateReminder\" type=\"text\" class=\"dateToPick\" " +
        "name=\"DateReminder\" value=\"").append(dateReminder).append("\" size=\"12\" " +
        "maxlength=\"10\"/>").append("\n");
    builder.append("</div>").append("\n");
    builder.append("</div>").append("\n");

    builder.append("<div class=\"field\" id=\"messageReminderArea\">").append("\n");
    builder.append("<label for=\"messageReminder\" class=\"txtlibform\">").append(
        this.messages.getString("dateReminder.message")).append("</label>").append("\n");
    builder.append("<div class=\"champs\">").append("\n");
    builder.append("<textarea rows=\"4\" cols=\"65\" name=\"MessageReminder\" " +
        "id=\"messageReminder\">").append(messageReminder).append("</textarea>").append("\n");
    builder.append("</div>").append("\n");
    builder.append("</div>").append("\n");

    builder.append("</div>").append("\n");

    builder.append("</fieldset>").append("\n");

    return builder.toString();
  }
}
