DELETE FROM ST_Component WHERE ID = 2;
DELETE FROM ST_Component WHERE ID = 3;
DELETE FROM ST_Component WHERE ID = 4;
DELETE FROM ST_Component WHERE ID = 5;
DELETE FROM ST_Component WHERE ID = 6;
DELETE FROM ST_Component WHERE ID = 7;
