<div id="footer">
$if(delay)$
Vous recevrez $delay$ une nouvelle synthèse de notifications.<br/>
Vous pouvez à tout moment changer la fréquence de réception de cette synthèse depuis le paramétrage de "Mes notifications" accessible depuis votre espace personnel.
$else$
Vous avez choisi de ne plus recevoir de synthèse de notifications.<br/>
Si vous le souhaitez, vous pouvez de nouveau recevoir cette synthèse via le paramétrage de "Mes notifications" accessible depuis votre espace personnel.
$endif$
</div>