create table SB_TREE_TREE_TEMP
as 
select SB_TREE_TREE.TREEID as TREEID, SB_TREE_TREE.ID as ID, SB_TREE_TREE.NAME as NAME, 
SB_TREE_TREE.DESCRIPTION as DESCRIPTION, SB_TREE_TREE.CREATIONDATE as CREATIONDATE, 
SB_TREE_TREE.CREATORID as CREATORID, SB_TREE_TREE.PATH as PATH, SB_TREE_TREE.LEVELNUMBER as 
LEVELNUMBER, SB_TREE_TREE.FATHERID as FATHERID, to_number(SB_TREE_TREE.ORDERNUMBER) as 
ORDERNUMBER from SB_TREE_TREE;

ALTER TABLE SB_Tree_Tree DROP CONSTRAINT PK_Tree_Tree;

DROP INDEX IN_SB_Tree_Tree_1;

DROP TABLE SB_Tree_Tree;

create table SB_TREE_TREE
as 
select SB_TREE_TREE_TEMP.TREEID as TREEID, SB_TREE_TREE_TEMP.ID as ID, 
SB_TREE_TREE_TEMP.NAME as NAME, SB_TREE_TREE_TEMP.DESCRIPTION as DESCRIPTION, 
SB_TREE_TREE_TEMP.CREATIONDATE as CREATIONDATE, SB_TREE_TREE_TEMP.CREATORID as CREATORID, 
SB_TREE_TREE_TEMP.PATH as PATH, SB_TREE_TREE_TEMP.LEVELNUMBER as LEVELNUMBER, 
SB_TREE_TREE_TEMP.FATHERID as FATHERID, SB_TREE_TREE_TEMP.ORDERNUMBER as ORDERNUMBER from 
SB_TREE_TREE_TEMP;

CREATE INDEX IN_SB_Tree_Tree_1 ON SB_Tree_Tree(path);

ALTER TABLE SB_Tree_Tree ADD 
	 CONSTRAINT PK_Tree_Tree PRIMARY KEY   
	(
		treeId,
		id
	)
;

DROP TABLE SB_Tree_Tree_TEMP;
