<div class="componentNav">

<span class="txtNav"> <center> Bienvenue sur le module Référentiel  </center> </span>
<br/>
Le référentiel contribue à organiser les domaines et les utilisateurs qui en font partie.
<br/>
Il permet de :
<br/>

<ul>

<li>
Gérer les domaines
<br/>
Un domaine est organisé en groupes d'utilisateurs et chaque groupe n'appartient qu'à un seul domaine.
<br/>
Il existe plusieurs types de domaines :
<ul>
<li>les domaines utilisateurs
<br/>
- $listDomains; separator="<br/> - "$
<br/>
On notera que le domaine <em>Silverpeas</em> existe par défaut.
<br/>
Les autres domaines peuvent être créés manuellement ou être branchés sur un annuaire externe.
</li>

<li>le domaine mixte
<br/>
Aucune création d'utilisateur n'est possible sur ce domaine.
<br/>
Ce domaine permet simplement de regrouper des utilisateurs provenant de différents domaines. 
</li>
</ul>
</li>
<br/>
<li>
Créer et gérer les groupes d'utilisateurs.
</li>
<li>
Importer les utilisateurs isolés et/ou les groupes.
</li>
<li>
Rechercher un utilisateur ou un groupe.
</li>	
<li>
Consulter l'ensemble des utilisateurs branchés sur la base de Silverpeas.
</li>	
<li>
Modifier ou supprimer les fiches des utilisateurs isolés ou les groupes.
</li>	

</ul>

</div>
