CREATE TABLE ST_User_2FA
(
    userId     INT          NOT NULL,
    secret     VARCHAR(1024) NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    createdAt  TIMESTAMP    NOT NULL,
    updatedAt  TIMESTAMP    NOT NULL,
    lastUsedAt TIMESTAMP,
    failedAttempts INT NOT NULL DEFAULT 0,
    lockedUntil TIMESTAMP
);

CREATE TABLE ST_User_2FA_Recovery
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    hash VARCHAR(64) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL,
    usedAt TIMESTAMP
);