ALTER TABLE ST_User_2FA
    ADD CONSTRAINT PK_User_2FA
        PRIMARY KEY (userId);

ALTER TABLE ST_User_2FA
    ADD CONSTRAINT FK_User_2FA_User
        FOREIGN KEY (userId)
            REFERENCES ST_User(id);